### ISSUE TITLE
Problem when displaying STEREO SECCHI EUVI images

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#10]
When displaying STEREO SECCHI EUVI images from 2009, they seem to be misaligned (see screenshot). 

![screen shot 2016-04-11 at 16 10 33](https://cloud.githubusercontent.com/assets/9073862/14430177/ce7fd27e-0000-11e6-9c46-758386cda1c2.png)

**Comment by freekv** [comment]
I see that for the stereo images at that instance have NAXIS2=512 instead of the usual 2048 for other frames close in time (i.e. they are only quarter of images). Hence the somewhat awkward jump from red to blue in the video. Unless you indicate something else?

**Comment by dmueller3000** [comment]
Thanks, Freek. Indeed, it looks like the STEREO A and B 171 Å images here are 2048x512 px in size rather than 2048x2048. Interestingly, the 304 Å images seem unaffected.

See also 
http://helioviewer.org/?date=2009-04-01T13:00:23.000Z&imageScale=4.84088176&centerX=0&centerY=0&imageLayers=%5BSTEREO_A,SECCHI,EUVI,171,1,100%5D&eventLayers=&eventLabels=true

@Jack & Serge: Could you check whether this is a data acquisition or processing issue?

Best,
Daniel

**Comment by bogdanni** [comment]
Could be campaign, see item 091 (JOP 216) on
http://stereo-ssc.nascom.nasa.gov/plans/plans2009.shtml

**Comment by dmueller3000** [comment]
I think this is in the source data.  The STEREO science center (SSC) 
does not have any images at the time given by the link below.  I think 
the SSC must have filtered those images out.

**Comment by dmueller3000** [comment]
Thanks, Jack!

**Comment by bogdanni** [comment]
This is most clearly an observation campaign, see also:
http://stereo-ssc.nascom.nasa.gov/minutes/2009/weekly_20090325.txt

"JOP 216, Multi-wavelength Observations of Oscillations in Polar Plumes
  Target is south pole/southern coronal hole"

Will close this, please reopen if you think there is something wrong with the rendering.
