### ISSUE TITLE
SECCHI HI-1 HI-2 imagery (Enhancement Idea)

### ISSUE THREAD

**Issue by live4right** [Helioviewer-Project/JHelioviewer-SWHV#104]
Good Morning, 

I had an idea about adding the Secchi HI-1 and HI-2 imagery to the JHelioviewer data options. I think that it would be helpful to have all the data available in one location.  The HI-1 and 2 STARS imagery was very useful in picking out comets at a distance. Do you think that it would be feasible to add that data source to the program?  https://secchi.nrl.navy.mil/index.php?p=js_secchi_day is the site that I use currently for the data.  Thanks for a great program. Have a nice day!

--Carl Berghoff

**Comment by bogdanni** [comment]
Thanks for the suggestion, it's on the to-do list!

**Comment by bogdanni** [comment]
A user sent this image, it should work since a while. Could probably be improved.
![image](https://user-images.githubusercontent.com/1223825/154137156-31ceaa3e-060e-4604-970b-62db6bc4eeb0.png)
