### ISSUE TITLE
Time Stamp not changing when tracking on

### ISSUE THREAD

**Issue by takucera** [Helioviewer-Project/JHelioviewer-SWHV#109]
Hi, I am trying to make a movie with jhelioviewer, just updated to Version 2.15.7.9411.
I see when the track feature is being use the time given by the time stamp does not update. I assume it shows the time corresponding to the time the tracking started, but I need to have the time of the individual data frames in the movies I save. Is there a way to do that?

**Comment by bogdanni** [comment]
Yes, it's the timestamp of tracking viewpoint. If you turn on multiview mode, the timestamp showed is of each particular layer, therefore if you have only one layer, it will show what you probably want.

**Comment by takucera** [comment]
Good, thank you!
