### ISSUE TITLE
Strange initial perspective when requesting long-duration AIA time series - disappears as soon as user starts playing the movie

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#111]
![Screen Shot 2019-03-26 at 09 39 20](https://user-images.githubusercontent.com/9073862/55001947-fba47c00-4fd5-11e9-9bc8-d50d72746953.png)

**Comment by bogdanni** [comment]
Known problem, to be fixed.
