### ISSUE TITLE
Server error when requesting SOHO LASCO time series with > 1000 frames from GSFC

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#113]
Instead of the server resampling the time series to stay below 1000 frames (as indicated in the first server message), the attached error message was displayed, and no new data was displayed at all.

![Screen Shot 2019-03-26 at 09 31 03](https://user-images.githubusercontent.com/9073862/55002264-943afc00-4fd6-11e9-9294-39e31159b0a4.png)

**Comment by bogdanni** [comment]
A transient error probably.
