### ISSUE TITLE
KCor data at GSFC not obtainable via JHV

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer-SWHV#114]
KCor image data has just become available at the archive at GSFC.  The latest version of JHV does not see those data.

**Comment by bogdanni** [comment]
This will be in JHV 2.15.8.

**Comment by bogdanni** [comment]
1. Shall this get HV_ROCC_INNER and HV_ROCC_OUTER?
1. Keep the gray colormap?

**Comment by bogdanni** [comment]
In the HV_COMMENT tag there are sequences "(ASCII character value=10)", probably where there were newlines in the original string.

**Comment by bogdanni** [comment]
Kcor is available in JHV for more than 4 years. For questions of data presentation or coverage, please open another issue.
