### ISSUE TITLE
User manual unavailable

### ISSUE THREAD

**Issue by d-lamb** [Helioviewer-Project/JHelioviewer-SWHV#115]
In the "Help" menu, the item "Open User Manual" opens a browser tab at the url http://swhv.oma.be/user_manual/.  This is also the same address that is pointed to by http://www.jhelioviewer.org/doc.html .  The server there has not responded for some time, so I don't think this is a temporary issue.  This might be related to the server migration mentioned in #107.

**Comment by d-lamb** [comment]
User manual seems to be have become available soon after this issue was created so I am closing it.

**Comment by bogdanni** [comment]
Thank you for the report. Yes, it is related to the lockup of the server and the unfinished server migration mentioned in #107.
