### ISSUE TITLE
Loading jp2 frames directly into JHelioviewer

### ISSUE THREAD

**Issue by AvijeetPrasad** [Helioviewer-Project/JHelioviewer-SWHV#119]
Hi,

I have a sequence of jp2 images saved locally, which I had downloaded through the SunPy API. Now I wish to load them into JHelioviewer for further analysis. Currently, it loads each jp2 image separately as a single layer. Is it possible to load all of them together as a sequence?

Here are the details of the system and version that I am using:
Version 2.15.7.9411 JHV/SWHV-2.15.7.9411 (x86_64 Mac OS X 10.15.1)
 Oracle Corporation JRE 1.8.0_231 1.8GB 4CPU OpenGL 4.1 INTEL-14.2.16

Thanks and regards
Avijeet

**Comment by bogdanni** [comment]
Dear Avijeet, this is not possible yet, but it's a top requirement. Will be implemented soon.

**Comment by bogdanni** [comment]
It will work with any supported files: JP2, JPX, FITS, JPG, PNG, etc.

**Comment by AvijeetPrasad** [comment]
Hi Bogdan,

Which version of JHelioviewer will be having this functionality?

Regards
Avijeet

**Comment by bogdanni** [comment]
Currently it is called 2.16. I just uploaded some builds at http://swhv.oma.be/download_test/ .
Hope it works for you. Load via File->Open Image Layer and then select your files with Shift for multiple selection. You may run into issues if you try to load in the order of thousands of images.

I'm working to make this possible via SAMP, such that this can be done programmatically from the SunPy environment. 

There are many changes related to the minimal version of Java, which is now 11. macOS and Windows packages bundle the necessary parts of Java and are somewhat tested. Linux packages are totally untested.
