### ISSUE TITLE
Problem with image quality

### ISSUE THREAD

**Issue by mihon4ik** [Helioviewer-Project/JHelioviewer-SWHV#12]
Hi! 

I want to report a very poor quality of imported images (video is also a concern) of new versions of software (JHELIOVIEWER 2.3.3; GET NEW JHELIOVIEWER 2.10; JHELIOVIEWER 3.0.8-beta). In older versions this was not observed (JHELIOVIEWER 2.1.0 - 2.2.1). 

Offer to view two images, 100% crop original images. 
First (4096х4096 2,57 Mb) loaded with SDO website (http://sdo.gsfc.nasa.gov/data/). Similar image quality was in older versions.
Second (4096х4096 531 Kb) exported via a new program JHELIOVIEWER 2.3.3; NEW JHELIOVIEWER 2.10; JHELIOVIEWER 3.0.8-beta. 

I would be very happy if the problem is solved, and everyone will be able to make beautiful high-quality videos : )

![1](https://cloud.githubusercontent.com/assets/18525804/14596994/b2d1c148-0552-11e6-9fcb-e07ce6a3ed87.PNG)
![2](https://cloud.githubusercontent.com/assets/18525804/14596993/b2d12080-0552-11e6-93c0-ea0edd38d86c.PNG)
![3](https://cloud.githubusercontent.com/assets/18525804/14597039/0081a8a4-0553-11e6-9514-bfa6d0d49711.PNG)
![4](https://cloud.githubusercontent.com/assets/18525804/14597040/008333e0-0553-11e6-9cae-81c2601d9c11.PNG)

**Comment by mihon4ik** [comment]
I will add that in the older versions was the ability to change the quality of the exported images (video).

**Comment by bogdanni** [comment]
Are you using a Mac? Because the versions <= 2.2.1 are not aware of Retina displays, you are seeing images zoomed beyond 1:1. The poor quality of the exported video is known, sorry about that, will be improved as soon as possible.

**Comment by mihon4ik** [comment]
No, I use and have used PC.

2016-04-18 11:17 GMT+03:00 Bogdan Nicula <notifications@github.com>:

**Comment by bogdanni** [comment]
But do you have a HiDPI display?

**Comment by mihon4ik** [comment]
22" 1680x1050

**Comment by bogdanni** [comment]
Version 2.10.2 will improve the quality of exported images. They will be difficult to tell apart from the input JPEG2000 files. See below for a comparison. Left is 2.10.1, right is 2.10.2. 
<img width="999" alt="hmi_rendering" src="https://cloud.githubusercontent.com/assets/1223825/15253226/b123d906-1931-11e6-847c-5f9d95d4e9d9.png">

**Comment by mihon4ik** [comment]
Superb! Thank you so much!

**Comment by dmueller3000** [comment]
Great! Thanks a lot, Bogdan.

Daniel
