### ISSUE TITLE
There are tons of other radio data (2-dimensional spectra) available for free

### ISSUE THREAD

**Issue by ChristianMonstein** [Helioviewer-Project/JHelioviewer-SWHV#13]
It's nice to see radio data from ROB. But I'm operating a worldwide network of solar radio spectrometers, called e-Callisto. This under the umbrella of UN and NASA in the framework of ISWI (International Space Weather Initiative). It would be really really really great if you could include these radio data into your application. Currentaly we have in the order of 120 instruments at 67 locations worldwide installed. 
General information here: http://www.e-callisto.org/
Free data access including quickviews here: http://soleil.i4ds.ch/solarradio/callistoQuicklooks/
or just data (FIT-files) here: http://soleil80.cs.technik.fhnw.ch/solarradio/data/2002-20yy_Callisto/
And we have data back to 2002 which inlcudes ROB data.

**Comment by bogdanni** [comment]
Dear Christian, the radio data we include is a composite merged from many e-Callisto instruments. This way we have 24h coverage.

**Comment by wreeve** [comment]
The Timelines Layer indicates that the data is only from ROB but to attain 24 hour coverage, there must be other observatories contributing data. Is there a way to determine which e-Callisto observatories are being displayed in the Timelines Layer?

**Comment by bogdanni** [comment]
The data from several e-Callisto stations are merged into a composite dataset and then transformed into a JHelioviewer specific JPEG2000 image file, one per day. This JPEG2000 file is available, for the time being, only the ROB Helioviewer server.

The list of the stations used is the following:
`ALASKA,BIR,BLEN7M,BLENSW,GAURI,HUMAIN,MRT1,MRT2,MRT3,OOTY,RCAG,ROSWELL-NM,SSRT,TRIEST`

The FITS files are downloaded from http://soleil.i4ds.ch/solarradio/data/2002-20yy_Callisto

Closing this. Please open a new issue if you want to discuss the merging of data.
