### ISSUE TITLE
Problem when open JHelioviewer

### ISSUE THREAD

**Issue by larrodera** [Helioviewer-Project/JHelioviewer-SWHV#137]
Hello,

when I try to open JHelioviewer, everythingseems to be ok, untilit crashed and showing the message from the attached image.
Could anyone please help me to solve it?

Thank you very much!
 
![Screenshot from 2020-03-20 12-37-36](https://user-images.githubusercontent.com/42888457/77160468-aa737f00-6aa7-11ea-8123-fed841af290d.png)

**Comment by bogdanni** [comment]
Please use the version 4 from http://swhv.oma.be/download_test/, it will be released in a few days.
