### ISSUE TITLE
Windows 10 version update?

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#149]
I see the linux version is being updated but nothing for the windows version. SWEK events don't load and always get STEREO-Ahead and SOHO never current images on the windows version. Please actively update the windows version.

**Comment by bogdanni** [comment]
The release of version 4.0 is imminent. The software is tested under all supported operating systems.
Preliminary builds can be downloaded from http://swhv.oma.be/download_test/

**Comment by simplio** [comment]
Thanks you bogdanni I'll book mark that in Edge Chromium. I am enjoying JHelioviewer. I am hobby level solar observer.
