### ISSUE TITLE
4k by 4k movie export question 

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer-SWHV#15]
Please see the last comment on https://github.com/Helioviewer-Project/helioviewer.org/issues/2 .

**Comment by bogdanni** [comment]
Replied: https://github.com/Helioviewer-Project/helioviewer.org/issues/2#issuecomment-216641350

**Comment by wafels** [comment]
How does a user export 4k by 4k movies using SWHV?  The help manual does not say.  Another user recently asked if SWHV could provide this functionality?

**Comment by bogdanni** [comment]
Currently it's possible to export only at window size, 720 and 1080. Exporting at 4k, which I assume the user means transferring the original AIA JP2s to frames of a movie, is a bit weird in the context of the various projections which are central to this program. There are complications also with the fact that movie generation is done on the fly and the computer may run out of memory if the encoding falls behind (we start skipping frames currently). Other issue is with the region-of-interest decoding of the JPEG2000 data.

My point of view that this is a tool for small WYSIWYG movies, and not a Swiss-Army tool for movie editing. We'll look into it, nevertheless.

**Comment by bogdanni** [comment]
@wafels : a 4k TV channel has a resolution of 3840×2160 (UHD-1, double in each direction of 1080 HD). UHD-2 has 7680×4320.
