### ISSUE TITLE
JHelioviewer Version 4.0.0.10109 Annotations Not Working

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#150]
I like to mark features on the sun when I find them. I tried doing what I did in the old version which was select circle then use the mouse to put a circle around like a leaping filament or anything else. In the new version All it would do is pan when trying to annotate a feature with no circle. The manual is for an old version. Is there instructions for version 4.0 somewhere?

**Comment by bogdanni** [comment]
Please keep the shift key pressed and draw, it is not anymore an interaction mode. Also shift+delete to remove, shift+n to cycle through the annotations.

**Comment by simplio** [comment]
That worked thanks!
