### ISSUE TITLE
JHelioviewer 4 Stops Loading-SOLVED!

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#151]
I have the Java Se 64 bit installed. It was working until this morning just won't load when clicking on it's shortcut and the executable in the JHelioviewer  executable in the bin folder. This is version 4 in the test build released October 7, 2020

**Comment by bogdanni** [comment]
JHV 4 comes with the Java it needs bundled inside. There is no need anymore for a separate Java installation. I'm not quite sure what is wrong, here it works both from the Start Menu and the program in the bin folder. Maybe try reinstalling it?

**Comment by simplio** [comment]
i tried that 3 or 4 times rebooted the computer each time. clicking on the shortcut does nothing.

**Comment by simplio** [comment]
I found this in the Windows Event Log

Faulting application name: JHelioviewer.exe, version: 0.0.0.0, time stamp: 0x5e5edc79
Faulting module name: kdu_a7AR.dll, version: 0.0.0.0, time stamp: 0x5a78ea97
Exception code: 0xc0000005
Fault offset: 0x0000000000017c45
Faulting process id: 0x21d8
Faulting application start time: 0x01d69e2cb32c9970
Faulting application path: C:\Program Files\JHelioviewer\bin\JHelioviewer.exe
Faulting module path: C:\Users\<redacted>\JHelioviewer-SWHV\Cache\lib2099615013679077506\kdu_a7AR.dll
Report Id: 96ad3c06-55aa-46f7-924f-6aa1e798538d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bogdanni** [comment]
This is tricky. You could try to remove the directory C:\Users<redacted>\JHelioviewer-SWHV

Did anything change on your computer since it was able to start? Could it be some antivirus interfering?

If you don't need system-installed Java for anything else, it may be prudent to uninstall it, just in the unlikely case that it's interfering somehow.

**Comment by simplio** [comment]
I tried to figure out in my mind what may have happened to cause JHelioviewer to stop loading after it was working. Re-installing it didn't fix it. Removing directories left behind then reinstallling didn't help. Adding to exclusions didn't help. Disabling real-time protection didn't help. I gave up and reinstalled the old version available from the main JHelioviewer site. 
I just hope JHelioviewer 2 has some life left. I might have to redo the entire windows system. I am trying not to do that to many times because it's on a Intel SSD + Optane Memory combination in the NVMe slot don't want to burn out the SSD.

**Comment by simplio** [comment]
Closing issue as not resolvable

**Comment by bogdanni** [comment]
If you allow me, I will make a few builds for you to try. It could be something inside Java...

**Comment by simplio** [comment]
That sounds fine

**Comment by bogdanni** [comment]
Could you please try again the exe from http://swhv.oma.be/download_test/ ?
If it starts for you, in the About dialog box it should say: JHV/SWHV-4.0.0.10116 (amd64 Windows 10 10.0) JetBrains s.r.o. JRE 11.0.8

**Comment by simplio** [comment]
It's downloading I'll let you know shortly.

**Comment by simplio** [comment]
Error log upon installation

java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Component.<clinit>(Component.java:626)
	at java.desktop/javax.swing.ImageIcon$2.run(ImageIcon.java:130)
	at java.desktop/javax.swing.ImageIcon$2.run(ImageIcon.java:128)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/javax.swing.ImageIcon.createNoPermsComponent(ImageIcon.java:127)
	at java.desktop/javax.swing.ImageIcon$1.run(ImageIcon.java:106)
	at java.desktop/javax.swing.ImageIcon$1.run(ImageIcon.java:103)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/javax.swing.ImageIcon.<clinit>(ImageIcon.java:103)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:193)
	at com.install4j.runtime.installer.frontend.GUIHelper.<clinit>(GUIHelper.java:52)
	at com.install4j.runtime.installer.helper.InstallerUtil.reportException(InstallerUtil.java:1235)
	at com.install4j.runtime.installer.Installer.main(Installer.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:198)
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:193)
	at com.install4j.runtime.installer.frontend.GUIHelper.<clinit>(GUIHelper.java:52)
	at com.install4j.runtime.installer.helper.InstallerUtil.reportException(InstallerUtil.java:1235)
	at com.install4j.runtime.installer.Installer.main(Installer.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by simplio** [comment]
not sure. i just noticed that error log pop up in the downloads folder where i downloaded the installer. trying to run it from either the bin folder or shortcut didn't load anything. I just can't understand why it would work for a day then stop loading even after installing so many times.

**Comment by bogdanni** [comment]
Did you install it? After double-clicking the installer exe, there should be a sequence of dialogs, like "install4j Wizard" etc.

**Comment by simplio** [comment]
yes installed it.

**Comment by bogdanni** [comment]
And then you receive that error message? Could you please post a screenshot of how that message is displayed? Thanks.

**Comment by simplio** [comment]
why is there h files in the win32 folder? those are linux version files

**Comment by simplio** [comment]
i think something fails in JavaFX. JHelioviewer shouldn't run with JavaFX. It's not a one size fits all thing.

**Comment by simplio** [comment]
no pop ups no nothing loading JHelioviewer for the upteenth time

**Comment by simplio** [comment]
without a debugger logging the actions while its loading no errors nothing displayed no wonder it cant be troubleshooted  if thats not happening then no use troubleshooting.

**Comment by bogdanni** [comment]
JHV does not use JavaFX, just Java, and I don't see Linux files in the Windows installation.
Sorry that it doesn't work for you.

**Comment by simplio** [comment]
Installed Java JDK 15 then it proceeded to work. It would not work without it. Re-opening to show the fix is make sure Java JDK 15 is installed and Environment Path is set.

**Comment by bogdanni** [comment]
Can you please post a screenshot of the About dialog box? Thanks.

**Comment by simplio** [comment]
![Screenshot 2020-10-17 114908](https://user-images.githubusercontent.com/53747770/96348497-d9b69280-106e-11eb-83e8-7d17f9513e0b.png)
That's what it shows

**Comment by bogdanni** [comment]
So, as expected, it does use the internally provided Java (JetBrains s.r.o. JRE 11.0.8). I'm astonished that installing Java 15 on your computer fixed it!

**Comment by simplio** [comment]
IF i remove JDK 15 itll fail to load again. Perhaps something was overlooked?

**Comment by bogdanni** [comment]
Maybe something in the install4j loader (the program that starts JHV itself). JHV is just a Java program, cannot see outside its protected Java environment. I'm going to write this off as spooky action at distance. 

Keeping open in case there is an update of install4j that solves this perplexing issue. Thank you for the persistence and enjoy JHV!

**Comment by simplio** [comment]
Okay leaving open in case install4j gets a update. I enjoy JHelioviewer. It had to do soething with a JNI error dialogue popup when I was troubleshooting my method by trying to load the JHelioviewer jar files from the JHelioviewer/classes folder. I googled the JNI error and it is related to Java JDK, 

Many others have had the JNI missing error and one example with other solutions is here. 
https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips

for now I leave it as is.

**Comment by bogdanni** [comment]
Are you trying to start JHV from the terminal? For version 4, it's not anymore a simple `java -jar JHelioviewer.jar`

For Windows should be something like:
`c:\Program Files\JHelioviewer\classes>..\jre\bin\java.exe -cp JHelioviewer.jar;natives-windows.jar org.helioviewer.jhv.JHelioviewer`

**Comment by simplio** [comment]
The shortcut in the start menu.
![Uploading Screenshot 2020-10-17 124410.png…]()

**Comment by bogdanni** [comment]
You don't need to create a batch file, there is a program in the bin folder which runs it the correct way. A shortcut for this program is created in the Start menu under the JHelioviewer folder.

For me, this now seems an interference from the previous installation of version 2, like trying to start it the old way. Could you please:

1. uninstall it 
2. remove `c:\Program Files\JHelioviewer`
3. in File Explorer go to `%AppData%\Microsoft\Windows\Start Menu\Programs`, check if you still have JHelioviewer items there and remove them
4. re-install JHV 4

**Comment by simplio** [comment]
JH2 was already removed before JH4 installed. JH4 is working as is. I was only stating what happened that caused me to install Java JDK15 then it worked.

**Comment by bogdanni** [comment]
I believe this was solved some time ago.
