### ISSUE TITLE
No Selection for GSFC Data & IAS Data is not Current

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#158]
JHelioviewer is not showing a selection for GSFC images at all. No drop down box.
![nogfsc](https://user-images.githubusercontent.com/53747770/107849835-6bd36b00-6dc3-11eb-9d8d-60f6a55eb8bb.png)

For IAS It won't allow me to select data for the current day.
![IASbehind](https://user-images.githubusercontent.com/53747770/107849895-d4224c80-6dc3-11eb-8fad-ad680e44aa7a.png)

**Comment by ebuchlin** [comment]
For IAS we are investigating. Our data come from GSFC, so either the GSFC JP2 file generation also lags behind, or the GSFC web redirection prevents us from synchronizing the files (URLs like https://helioviewer.org/jp2/AIA/ are also redirected).

**Comment by bogdanni** [comment]
This was a transient server side issue. Fixed in the meanwhile.
