### ISSUE TITLE
Export Movie - use H.264 codec

### ISSUE THREAD

**Issue by ddialer** [Helioviewer-Project/JHelioviewer-SWHV#16]
I suggest to change video codec form MPEG to H.264. 

I noticed that JHelioviewer using regular MPEG codec when exporting the movie. Unfortunately, regular MPEG codec is not supported by most of the modern browsers (https://en.wikipedia.org/wiki/HTML5_video). And, to upload the exported movie, a user needs to convert the movie using H.264 codec so that it can be played on the web.

 For Helioviewer.org we are using this command to generate mp4 movies using H.264 codec:
```
ffmpeg 
	-r 15 
	-i /data/frames/frame%d.bmp 
	-vcodec libx264 
	-pix_fmt yuv420p 
	-preset ultrafast 
	-threads 8 
	-crf 15 
	-s 452x206 
	-an 
	-y /data/movies/0BLd5/2016_05_09_10_58_21_2016_05_09_14_23_06_HMI_Int-hq.mp4 2>/dev/null
```

**Comment by bogdanni** [comment]
The next version (2.10.2), soon to be released, exports using H.264 codec (https://github.com/Helioviewer-Project/JHelioviewer-SWHV/commit/60de82d4f8c91c0cf8378668cb5965b9e3c9e25e). For hv.org I suggest to use tailored parameters per data set (HMI continuum is very different from AIA EUV, for example).
