### ISSUE TITLE
"Fatal error" when starting to modify a Preference and than canceling (but 

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#160]
Go to Preferences, select "At start-up: Load State", click on "Select State", than "Cancel" --> "fatal error" (but I can press "Continue" and keep using JHV).

I was actually looking for a way to load the most recent 48h of AIA 171 as default, but then discovered this feature. What is the specific use case for it? Can a state file specify "most recent x hours of instrument y"?

Thanks!

Daniel

![Screen Shot 2021-04-02 at 15 18 48](https://user-images.githubusercontent.com/9073862/113419020-e0d81f80-93c6-11eb-85e1-aecb36c66d96.png)

**Comment by bogdanni** [comment]
Sorry for the exception.

The use case is that the user can configure the program to start in a preferred configuration (e.g., miniview off, grid Carrington, timestamp on, viewpoint Solar Orbiter, etc.).

A state file can specify start="48 hours ago", end="now", but this has to be manually typed in the state file.

**Comment by bogdanni** [comment]
The "default movie" feature was interfering with this "default state" feature. This new feature is more powerful, but admittedly not as user friendly as of now. A solution is to ship the program with a similar prewritten state.

**Comment by dmueller3000** [comment]
Ah - thanks a lot! That's indeed a very powerful feature. I'll have a think about how we could make it even more user-friendly. Happy Easter!
