### ISSUE TITLE
Annotations not working

### ISSUE THREAD

**Issue by weaselskinghenry** [Helioviewer-Project/JHelioviewer-SWHV#165]
I've been using the last version of JHelioviewer and now I just updated to the current version. In both, when I click the annotation option and try to select features, nothing comes up on the disk. I'm working on a MacBook Pro running Catalina 10.15.7, nothing special about it. Is anyone else having this issue?

**Comment by bogdanni** [comment]
Sorry, the user manual is not updated: you have to press the Shift key and draw with the mouse. When done, release the key.

**Comment by weaselskinghenry** [comment]
Ok, thank you!
