### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#167]
JHelioviewer connection was refused. 

![image](https://user-images.githubusercontent.com/53747770/121940151-622b2700-cd13-11eb-9edf-68298f0dfeb7.png)

**Comment by bogdanni** [comment]
GSFC servers undergo maintenance, please excuse the service interruption.

**Comment by simplio** [comment]
When is the estimated time to be back up?

**Comment by simplio** [comment]
> GSFC servers undergo maintenance, please excuse the service interruption.

Well I know GSFC is back up because SDO The Sun Now is working, helioviewer.org is working but JHelioviewer gets refused.
