### ISSUE TITLE
HMI Out Dated GSFC & IAS

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#168]
I find that I can't analyze previous 24 hours of HMI Continuum and HMI Magnetogram in JHelioviewer because both GSFC and IAS report the same "Error getting the data" pop up message. However, SDO The Sun Now shows to be current near real time. 

![image](https://user-images.githubusercontent.com/53747770/122816457-5d7aeb80-d29c-11eb-8b17-ff4d5c7e2c0b.png)

Please fix it.

**Comment by ebuchlin** [comment]
Latest HMI magnetogram file at GSFC seems to be [2021_06_17__13_42_38_500__SDO_HMI_HMI_magnetogram.jp2](https://helioviewer.org/jp2/HMI/2021/06/17/magnetogram/2021_06_17__13_42_38_500__SDO_HMI_HMI_magnetogram.jp2) (file date is 2021-06-17 16:14), so yes, JP2 file production seems to be delayed.

**Comment by simplio** [comment]
It's very important to me to review HMI Magnetogram because of the phase of SC25 currently for every 24 hours. I really need this to be current. Can't use Helioviewer web because the zoom levels do not get close enough like JHelioviewer can. Noticed some subtle changes in the magnetic equator (AIA171) a day or so ago that must be followed up on using HMI.

**Comment by wafels** [comment]
I'll take a look.

**Comment by wafels** [comment]
I think I've located the source of the problem, and I'm working on a fix.

**Comment by simplio** [comment]
Thanks Wafels!

**Comment by wafels** [comment]
The issue is that the most recently available HMI files are from times earlier than the start of the time range that we look for data in. I have implemented a fix that looks for HMI data in earlier time ranges. HMI data should now be available on the server. I'll leave the fix running and check back in a few hours.

**Comment by simplio** [comment]
Only 9 images in a 24 hour time. Should be more.
