### ISSUE TITLE
Sourceid numbers for data not at GSFC

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer-SWHV#17]
Do you have a list of sourceid numbers for the image data not held at GSFC? The reason I ask is that I will be adding some new image sources at GSFC and i don't want any conflicts between sourceid numbers at different servers. We should have a master list somewhere.

**Comment by freekv** [comment]
We have currently assigned sourceids from 36 to 52 (both included), but we can easily change to other ids if that is more convenient.

**Comment by wafels** [comment]
Thanks!  At some point I'd like to start copying the image data ROB has
that GSFC does not have.  Assigning the same data to a given source id
number across different servers is important.

API v2 source ID's are at

http://api.helioviewer.org/docs/v2/#appendix_datasources.

I think the gap between source id 36 to 74 was intended for Hinode XRT
sources.  We may have those numbers assigned tentatively.

Am I right in thinking that we can use any number as a source id?  There is
no requirement for them to be sequential?

**Comment by freekv** [comment]
There is indeed no need that I am aware of for them to be sequential.

**Comment by bogdanni** [comment]
We do have an exception: the Callisto radio composites dataset. In JHV 2.10.4 we will need to hardcode the source id on the client side, so we would like a reserved id before the release. Currently on our server it is "49", but it's not big deal to change it before release.

**Comment by bogdanni** [comment]
We moved Callisto to source ID 5000, please consider it reserved. All the others can be remapped transparently. For the time being, the stability of the rest of source IDs on ROB server is not very important. Closing this.
