### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/JHelioviewer-SWHV#176]
I do not know if it is related to updating to Windows 11 or there is actually a internal server error.
![image](https://user-images.githubusercontent.com/53747770/138607678-4d44e242-56c4-4f4b-bf6a-34ad62a82ac1.png)

**Comment by ebuchlin** [comment]
It seems that some files were corrupted (maybe because they were being downloaded at the start of the power outage). We have deleted and re-downloaded all files from 2021-10-23. Please tell us if you encounter the same issue on another date.
