### ISSUE TITLE
 IAS Server

### ISSUE THREAD

**Issue by sflorg** [Helioviewer-Project/JHelioviewer-SWHV#185]
Seems to be down. Any clue how long this issue will be? This is always the only one that had worked for me for current images.

**Comment by bogdanni** [comment]
It will probably be restored to service next week. In the meanwhile, you can download the test version from http://swhv.oma.be/download_test/ which enables the GSFC beta server.

**Comment by sflorg** [comment]
Thank you for the quick response, downloaded and will be testing shortly. Heidi-Ann

**Comment by ebuchlin** [comment]
Please see Helioviewer-Project/JHelioviewer-SWHV#179

**Comment by sflorg** [comment]
> Please see #179

Thank you for the information "ebuchlin", fortunately the GSFC Beta server took care of some of our needs as directed by "boddanni" minus the HMI Images. BTW folks, glad to see dark mode in new beta. 👍
