### ISSUE TITLE
Shortcut to minimise JHV window would be helpful

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#19]
E.g. Meta-M on Mac.

Thanks a lot!

**Comment by bogdanni** [comment]
Hide (cmd-h) will not work for you? A menu command will involve a new 'Window' menu entry with a lonely item. It's also rather alien on Windows.

**Comment by dmueller3000** [comment]
Thanks, that works fine for me.
