### ISSUE TITLE
Unable to synchronise the time series with the movie

### ISSUE THREAD

**Issue by pjiggens** [Helioviewer-Project/JHelioviewer-SWHV#191]
I see several buttons for synchronisation, the first for synchronising the image layers, the second perhaps for layers other than the one selected to the one selected (?) and the third to synchronise the images to the time series.
![image](https://user-images.githubusercontent.com/23653159/149913904-c84c82c7-6d3b-4703-bdc0-af284c4357a9.png)
I cannot see how to synchronise the time series to the movie so I'm always stuck in the present. There may be a connection to Issue #186

**Comment by bogdanni** [comment]
"Movie interval" in the dropdown box just next?

**Comment by pjiggens** [comment]
Clearly user error - closing!
