### ISSUE TITLE
Error when trying to create a video

### ISSUE THREAD

**Issue by cristianmircea** [Helioviewer-Project/JHelioviewer-SWHV#194]
Hi, when trying to create videos I am getting this error message, please see screenshot.
Is it a JHelioviewer bug or is it a compatibility problem with my computer/software?
Thanks.

![Screenshot (3200)](https://user-images.githubusercontent.com/99078697/152642573-c9f3a6ca-753e-4e42-97eb-7ea1a11bf6a8.png)
e

**Comment by bogdanni** [comment]
Please use the IAS or GSFC Beta servers. The regular GSFC server is temporarily not fully operational for JHV.

**Comment by cristianmircea** [comment]
Thank you, Bogdan!

**Comment by bogdanni** [comment]
GSFC is back in business.
