### ISSUE TITLE
Server/data unavailable

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/JHelioviewer-SWHV#196]
Hi,
The IAS server is currently not accessible in JHelioviewer 4.3.2
GSFC-beta is limited available, currently only one AIA frame every 10 minutes (at least for the last few hours)

**Comment by ebuchlin** [comment]
We seem to have a network hardware issue, IT team will try rebooting it.

**Comment by ebuchlin** [comment]
As last time, the heliovoewer database also had to be repaired. This is done now, and the system is back to operations. But the latest images are now 2 days old — catching up.

**Comment by bogdanni** [comment]
@ebuchlin Could you please have a look also at #193?

**Comment by bogdanni** [comment]
Thanks!

**Comment by helioshk** [comment]
Thank you, IAS server looks good.
But GSFC (beta) still has issues. It has only one AIA image every 11/12 minutes, instead of the usual 36 seconds. It would be good if that could be fixedl, to have a backup.

**Comment by farm24** [comment]
also for some reason, I still can't access the GSFC, GSFC beta, or IAS servers and the ROB is basically useless

**Comment by bogdanni** [comment]
GSFC beta works here. Indeed IAS is down, and GSFC returns an error.
Transferring to API project.
