### ISSUE TITLE
Speed adjustment panel: handling of user entries outside allowed range

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#2]
The speed adjustment panel works fine when using the preset value, when modifying it with the arrow buttons, or when typing in a number within the permitted range (1060) and then hitting return. However, when a user types in a number ouside this range, say '100' or '-10', no user feedback is given. The number remains in the field, but the actual value used seems to be the last value within the permitted range. 

My suggestion would be to inform the user about the permitted range and reset any values larger than the maximum to the max. value (60) and any negative values to the default value (20 fps).

**Comment by bogdanni** [comment]
fixed
