### ISSUE TITLE
when i try to access the GSFC it gives me a error

### ISSUE THREAD

**Issue by farm24** [Helioviewer-Project/JHelioviewer-SWHV#200]
when I try to access the GSFC server to get images it gives me this error
<img width="666" alt="Screen Shot 2022-03-05 at 11 57 48 AM" src="https://user-images.githubusercontent.com/77849362/156895048-08f9ada8-f2a3-4d6d-b46a-14e7cdaecf2c.png">

**Comment by bogdanni** [comment]
This is transient error from the server.
If it persists after a few days, please open a report against https://github.com/Helioviewer-Project/api
