### ISSUE TITLE
error on Raspberry pi OS (debian with Raspberry Pi Desktop)

### ISSUE THREAD

**Issue by farm24** [Helioviewer-Project/JHelioviewer-SWHV#201]
i have Raspberry pi desktop OS on a computer but when i try to open jhelioviewer it gives me this error
![2022-03-29-202947_1366x768_scrot](https://user-images.githubusercontent.com/77849362/160733026-d548b86e-66b8-417d-9f4e-d791e351e8ca.png)

**Comment by bogdanni** [comment]
That OS is not supported.

But is `libstdc++.so.6` for the AMD64 architecture included in some package you can install? That's a standard system library for a regular distribution. I guess this OS transparently uses `qemu` to run AMD64 binaries. Even if it finally works, I expect it to be very slow.

**Comment by farm24** [comment]
> That OS is not supported.
> 
> 
> 
> But is `libstdc++.so.6` for the AMD64 architecture included in some package you can install? That's a standard system library for a regular distribution. I guess this OS transparently uses `qemu` to run AMD64 binaries. Even if it finally works, I expect it to be very slow.

I installed arch and installed jhelioviewer and it works and pretty well too

**Comment by bogdanni** [comment]
Arch for ARM64? I'm amazed.

**Comment by farm24** [comment]
> Arch for ARM64? I'm amazed.

No I said I was running raspbian on a laptop

**Comment by bogdanni** [comment]
The only CPU architecture supported for the time being is AMD64/x64.
There is a report from a user running it on a M1 Mac via the Rosetta 2 translation.

Support for macOS and Linux ARM64/aarch64 will be added once I get a computer able to run those.

**Comment by farm24** [comment]
> The only CPU architecture supported for the time being is AMD64/x64.
> 
> There is a report from a user running it on a M1 Mac via the Rosetta 2 translation.
> 
> 
> 
> Support for macOS and Linux ARM64/aarch64 will be added once I get a computer able to run those.

I run it on my MacBook M1 just fine off of the original disk image with no extra stuff
