### ISSUE TITLE
1080 res in JH

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/JHelioviewer-SWHV#202]
Hi, i want to ask, why when i record with JH at 1080, the recorded video doesn't show exactly what i have select on the screen before the record. Example, i record log-polar, and on the "flat" area of the Sun (top of the view with log-polar), need to record more left, to the final resault is in view. I don't have 1080 res monitor, but, is that the "problem"? Or need specific settings? Thanks

**Comment by bogdanni** [comment]
The scene is rendered twice when you record, once at the desired output resolution and once at the screen resolution.
If the aspect ratio between output and screen viewport is different, it is normal that some areas outside the viewport may end up in the output. The screen viewport is usually more "squarish" than the preset output sizes.
