### ISSUE TITLE
Hinode XRT images are now available at GSFC

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer-SWHV#21]
Hinode XRT images are now available via helioviewer.org from the GSFC server, for example,

https://helioviewer.org/?date=2016-02-02T17:43:35.000Z&imageScale=4.84088176&centerX=298.92444868&centerY=183.95350688000002&imageLayers=%5BHinode,XRT,Be_thin,Open,1,100%5D,%5BSDO,AIA,131,1,97%5D&eventLayers=&eventLabels=true

https://helioviewer.org/?movieId=sqdh5

SWHV should be updated to make these images streamable.

**Comment by bogdanni** [comment]
Could you please check rev 8043 from http://swhv.oma.be/download_test/ ?

**Comment by wafels** [comment]
I made a movie.  Is everything re-projected on to a sphere?

[JHV_2016-11-09_16.40.58.mp4.zip](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/files/581383/JHV_2016-11-09_16.40.58.mp4.zip)

![screen shot 2016-11-09 at 11 57 02 am](https://cloud.githubusercontent.com/assets/983575/20146966/fe27c3d2-a673-11e6-98f6-c1cc4a977918.png)

Funnily enough, after playing around with the reprojection functions, the curved view went away.
![screen shot 2016-11-09 at 12 03 19 pm](https://cloud.githubusercontent.com/assets/983575/20147070/8826c844-a674-11e6-8fac-bb40d46cbd59.png)

[JHV_2016-11-09_17.01.24.mp4.zip](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/files/581397/JHV_2016-11-09_17.01.24.mp4.zip)

But then there was another issue with re-projection
![screen shot 2016-11-09 at 12 01 05 pm](https://cloud.githubusercontent.com/assets/983575/20147092/a931daba-a674-11e6-9f01-e46e6ed5ab1f.png)

**Comment by bogdanni** [comment]
For the first screenshot you had the camera (viewpoint) rotated. Yes, it's mapped on a sphere. The mapping is such that, if there is no rotation, it's precisely the image plane as captured. The camera is reset when you change projection, that's why you get the second screenshot.

There is a problem indeed in the latitudinal projection.

**Comment by freekv** [comment]
To be more precise : the image is not distorted for the active image layer only (indicated in bold in the layers list), if the viewpoint is reset (default at startup) and if the default viewpoint is chosen. Other images are derotated on a sphere, depending on their original viewpoint and timestamp.
See also http://swhv.oma.be/user_manual/#camera for a better understanding.

I solved the issue with the latitudinal reprojection.

**Comment by wafels** [comment]
I conform that the issue with the latitudinal re-projection has been fixed.
