### ISSUE TITLE
Force HTTPS Redirection

### ISSUE THREAD

**Issue by mbiesiad** [Helioviewer-Project/JHelioviewer-SWHV#210]
Force HTTPS Redirection

## Expected Behavior
Forced HTTPS Redirection

## Current Behavior
Connection with the site is marked as 'dangerous' (http instead of https)

## Steps to Reproduce (for bugs)
Type http://www.jhelioviewer.org/ instead of https://www.jhelioviewer.org/
See the mentioned issue.
(by the way, the mentioned site is often provided in form with "http://")

Best wishes,
Michal

**Comment by bogdanni** [comment]
Now it redirects and most (possibly all) uses of HTTP were replaced with HTTPS.
For the record, there's nothing inherently "dangerous" about this website when using HTTP.

**Comment by mbiesiad** [comment]
Hi @bogdanni Thanks for message and fix here, really appreciate it. Just quick note - from my point of view it don't have to be logging in or similar via unsafe HTTP. In some cases single use of HTTP site can be dangerous for victim (info about used site). Just short note from me. Best wishes,
