### ISSUE TITLE
JHelioviewer not loading data

### ISSUE THREAD

**Issue by tootgd** [Helioviewer-Project/JHelioviewer-SWHV#212]
Recently updated version of JHelioviewer.  Cannot load data from any sources.  (Have tried several)  Different errors at different sources.
For example, at SDO there is a protracted message that ends with a file type error.

**Comment by ebuchlin** [comment]
Probably linked to [api issue #159](https://github.com/Helioviewer-Project/api/issues/159).

**Comment by bogdanni** [comment]
Those were transient server errors.
