### ISSUE TITLE
User manual out of date

### ISSUE THREAD

**Issue by TrestanSimon** [Helioviewer-Project/JHelioviewer-SWHV#214]
It appears that some aspects of the user manual are out of date. I have noticed in particular that the annotation feature has changed since the manual was last updated (as mentioned in https://github.com/Helioviewer-Project/JHelioviewer-SWHV/issues/165#issuecomment-853400359). Additionally, the current GUI and toolbar differ from that shown in the example diagrams (e.g., [docs/user-manual/projection_1.png](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/blob/5fbedf689cc49879c770b56c2165361f55ad1e94/docs/user-manual/projection_1.png)).

**Comment by bogdanni** [comment]
That's absolutely right, the manual lags considerably. It's in the process of being updated. Thanks!

**Comment by TrestanSimon** [comment]
Updated in [4.3.3](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/releases/tag/4.3.3)
