### ISSUE TITLE
Problems with downloading EUI data

### ISSUE THREAD

**Issue by AlexanderWarmuth** [Helioviewer-Project/JHelioviewer-SWHV#217]
I cannot download EUI images. When using the ROB archive, I get error messages like this: "java.net.ConnectException: Connection timed out: connect: jpip://swhv.oma.be:8090/movies/SOLO_EUI_FSI_174_F2021-09-08T16.57.30Z_T2021-09-08T17.57.30ZB60L.jpx"
When I try the ESAC archive, I get this: "Duplicated time stamps: jpip://soarjpip.esac.esa.int/movies/SOLO_EUI_FSI_174_F2021-09-08T16.57.30Z_T2021-09-08T17.57.30ZB60L.jpx"
I am using the latest JHelioviewer version. With helioviewer.org, EUI works just fine. Could you please look into that?

Best regards,
Alexander Warmuth

**Comment by bogdanni** [comment]
This works correctly now on ROB server, on the ESAC server it still leads to "Duplicated time stamps" error due to incorrectly ingested data. The latter error will most likely be fixed by a proper installation/ingestion at ESAC site.
