### ISSUE TITLE
Available Data button in Timeline layers pane

### ISSUE THREAD

**Issue by pjiggens** [Helioviewer-Project/JHelioviewer-SWHV#22]
version 2.10.7 revisions 7995
There is an available data button in the timelines pane but it sends the user to the image data availability url. In the image layers pane the availability button is only visible after clicking on new layer.
Additionally I cannot find the availability for the Callito radiogram images on either web page.

**Comment by bogdanni** [comment]
Each timeline layer, including Callisto, has an availability button in its panel of options.
In case of Callisto it's http://swhv.oma.be/availability/images/availability/availability.html#IID5000
(on the image web page as it's an image dataset).

Can you please confirm that clicking one of those buttons in a timeline options panel sends you to the image availability web page? This may be a case of an old, pre-release, setting interfering. Could you please remove the file `user.properties` from the `JHelioviewer-SWHV/Settings` directory?

The availability button in the New Layer dialog boxes is shared between the images and timelines dialog boxes as much of the code. This button is disabled when an image dataset from another server than ROB is selected. There is indeed a sequence of actions (involving canceling the dialog) which may leave the button disabled. The code for the dialog boxes is now in the process of getting separated and this issue will be solved for the next release (2.10.8).

Nevertheless, depending on context, the button always points to the appropriate image or timeline availability URL, respectively, in my copy.

**Comment by pjiggens** [comment]
Ok, the button disappeared now I removed the user.properties file so that's fine and I think the Callisto radiogram data appears in the image availability at ROB radio data? It's a bit strange only because it's in the timeline layers pane.

**Comment by bogdanni** [comment]
Callisto data is image based, thus it uses the image datasets infrastructure.
Please reopen if you still encounter problems.
