### ISSUE TITLE
Timestamp freezes in "track" mode

### ISSUE THREAD

**Issue by eimason** [Helioviewer-Project/JHelioviewer-SWHV#222]
Hi all, when you are tracking a feature and you have the timestamp turned on, it only ever shows the timestamp of the frame when you turned tracking on (see example [here](https://drive.google.com/file/d/1-Ki21xSF03hr_Lkkk3w8c3N7__r_QbXp/view?usp=share_link)). It would be really helpful if the timestamp instead updated with each frame! Thanks 👍

**Comment by bogdanni** [comment]
Track mode is implemented by "freezing" viewpoint time. That's the reason for which the timestamp doesn't change.
If you want timestamp to show observer time, please turn on Multiview mode.

**Comment by eimason** [comment]
Ahh, I didn't know I could use multiview with a single channel...great, thank you!
