### ISSUE TITLE
Minimum movie interval is one hour?

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#227]
Version 4.4.0.10751 JHV/SWHV-4.4.0.10751 (amd64 Linux 5.19.0-32-generic) Eclipse Adoptium JRE 19.0.1 

JHV always returns images of one hour instead of given several minutes.

I wanted to get a very short movie of about three minutes.
For example, I set the time range from 2016-07-12T22:42:00 to 2016-07-12T22:45:00 in the input boxes below "Options".
It means I just need JHV to retrieve data of three minutes. 
And then I chose IAS/SDO/AIA 131 data in "New Layer".
However, I found that JHV returns a movie of one hour.
I checked the "New Layer" options has been set to "Custom interval".
Sounds like JHV just ignored the given three-minute interval.

I tried to modify the movie interval and set the "Time step" to 10 sec by double click the layer in the "New Layer" boxes,
but it persistently ignores it.

Is the "one hour" minimum interval intentionally setup?

Thanks.

**Comment by bogdanni** [comment]
Yes, this minimum is intentional.

**Comment by GitatHub** [comment]
Thank you. But is it possible to set this option as a user configure instead of a hard-coded one?

> If you care much about that, set `RANGE_EXPAND` to 0 at
> 
> https://github.com/Helioviewer-Project/JHelioviewer-SWHV/blob/9bb00260a65b177e6060d86aabe1effde758e8e4/src/org/helioviewer/jhv/io/APIRequest.java#L11
> 
> To compile the source tree you need only `ant` and a JDK > 19 in the PATH.
