### ISSUE TITLE
Adjusting time cadence of images layers does not always work

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#228]
A colleague reported the following (using JHelioviewer v4.3.2.10674 on MacOS 13):

It seems as though each new layer you add defaults to 97 images, adjusting the cadence to deliver that many images over the selected time span. By double-clicking on the layer, you get a pop-up window that allows you to specify the interval between images and thus (if so desired) get many more than 97 in the sequence.

     The problem is that that pop-up window only seems to work sporadically in a pattern I can’t fathom. That is, if I change the interval from 6 hours to 1 hour, say, then click “Change”, nothing actually changes. If I double-click to get the pop-up again, it says 6 hours again. I change it and save it, but again, nothing changes. Sometimes it takes 5-6 goes at this before the change is actually accepted – sometimes it happens after just 2 goes.

**Comment by bogdanni** [comment]
Can you reproduce this? This area hasn't changed in a long time.

**Comment by dmueller3000** [comment]
I am unable to reproduce it using the Mac OS 13.5 and the latest JHV, so am closing it.
