### ISSUE TITLE
Ordering of layers in multi-view mode cannot be changed by the user

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#23]
Use case: A user loads a number of image layers and wants to have them appear in multi-view mode in a specific order, e.g. 3 panel mode with LASCO data in the wide bottom panel, or 2 HMI layers in adjacent panels. Intuitively, we would expect the display order to be determined by the order in the layer manager, but this does not seem to be the case (it rather seems as if each layer is assigned a fixed "number" at load time). Proposal: We suggest that the order in multi-view mode should reflect the order of (checked) layers in the layer manager.

Thanks!
Daniel & Piers

**Comment by bogdanni** [comment]
Agreed that the proposed behaviour is more intuitive. However, it is a bit difficult to implement it right now.
