### ISSUE TITLE
IAS/GOES in jhelioviewer

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/JHelioviewer-SWHV#230]
I noticed that GOES images are available on the helioviewer.org website, but not in jhelioviewer. 
Could the GOES images on the IAS server be made available in JHV too?

They are available on the ROB server, but it seems to have issues right now (Connection refused)

**Comment by bogdanni** [comment]
ROB server restored.

**Comment by bogdanni** [comment]
This was happening due to an inconsistent platform name between servers: GOES at ROB, GOES-R for the rest.
This was corrected on ROB server and JHV was updated, please use the build from http://swhv.oma.be/download_test/

**Comment by helioshk** [comment]
Thanks!
ROB is working again, but on the other servers it's producing errors:

```
Error encountered during JPX creation: Error creating JPX file
COMMAND:
PATH="" /usr/local/bin/kdu_merge -s /dev/stdin
ARGUMENTS:
-i /var/www/jp2/SUVI/2023/03/28/304/2023_03_28__14_16_00__GOES-R_GOES-R_Series_Solar_Ultraviolet_Imager_(SUVI)_SUVI_304.jp2,/var/www/jp2/SUVI/2023/03/28/304/2023_03_28__14_44_00__GOES-R_GOES-R_Series_Solar_Ultraviolet_Imager_(SUVI)_SUVI_304.jp2,
[snip...]
/var/www/jp2/SUVI/2023/03/29/304/2023_03_29__17_12_00__GOES-R_GOES-R_Series_Solar_Ultraviolet_Imager_(SUVI)_SUVI_304.jp2,/var/www/jp2/SUVI/2023/03/29/304/2023_03_29__17_44_00__GOES-R_GOES-R_Series_Solar_Ultraviolet_Imager_(SUVI)_SUVI_304.jp2 -links -o /var/www/jp2/movies/GOES-R_SUVI_304_F2023-03-28T14.12.21Z_T2023-03-30T16.06.20ZB1871L.jpx
RETURN VALUE: 3
OUTPUT:
```

**Comment by ebuchlin** [comment]
Yes, I have also seen this error. I don't understand it, as we have the SUVI files corresponding to the error I got, and we can get the JPX for SDO/AIA or for the new SO/EUI dataset.

**Comment by bogdanni** [comment]
You may try to copy-paste the command in a shell on the server and investigate what goes wrong.

**Comment by bogdanni** [comment]
The actual command to try is something like
`echo '-i /var/www/jp2/SUVI/... -links -o /var/www/jp2/movies/...' | /usr/local/bin/kdu_merge -s /dev/stdin`

I think somebody from NASA modified my code "*for security reasons*" to add a check on allowed characters. Maybe the solution is to add '(' and ')'.

**Comment by bogdanni** [comment]
This [commit](https://github.com/Helioviewer-Project/api/commit/8dfdb2c3f44095a5c563f9e5888ea5f6eee22a79) is nonsense, IMHO.

**Comment by helioshk** [comment]
escapeshellcmd() ?

**Comment by bogdanni** [comment]
Those are files already on the secure server and their names are given to the 'kdu_merge' program on the same server. I don't get it.

**Comment by bogdanni** [comment]
Filed https://github.com/Helioviewer-Project/api/pull/278.

**Comment by helioshk** [comment]
I'm not sure where to leave this, but ROB doesn't have new GOES/SUVI images since March 30 12:00

**Comment by bogdanni** [comment]
Thanks, we'll look into it.

**Comment by bogdanni** [comment]
Processing was restored today. It started failing when I renamed the platform to GOES-R. Other servers should be unaffected. The gap since March 30 will be filled in the next couple of weeks.
