### ISSUE TITLE
is it possible that in previous versions, some observation options (ile SUVI) are automatically removed?

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/JHelioviewer-SWHV#231]
because in version 4_2_0 it SUVI doesn't exist anymore.

**Comment by bogdanni** [comment]
Please use version 4.4.2 which allows loading SUVI from all servers. There was a slight change in naming of the platform (GOES -> GOES-R).

**Comment by Anthrwpos** [comment]
OK, but could SUVI have been automatically removed from version 4_2_0? I had it for sure.

**Comment by bogdanni** [comment]
The satellite name changed on the server side and it's not recognised anymore on the client side.
