### ISSUE TITLE
STAFF x-ray (longwave)

### ISSUE THREAD

**Issue by pjiggens** [Helioviewer-Project/JHelioviewer-SWHV#24]
Very minor one but when one selects the 1-8 nm x-ray channel (not STAFF) you get the x-ray flare classification, with the STAFF selection you get the flux units (W/m2)

**Comment by bogdanni** [comment]
Cannot reproduce, for me all x-ray longwave (GOES XRS-B aka ODI, EVE XRS-B proxy, and STAFF XRS-B) appear to give values in the flare classification scale on mouse hover.

**Comment by bogdanni** [comment]
Please reopen if you still encounter problems.
