### ISSUE TITLE
No AIA data avilabe error message although there exist data

### ISSUE THREAD

**Issue by averonig** [Helioviewer-Project/JHelioviewer-SWHV#244]
Hello,

when I try to look at AIA data for 29-Sep-2023 11:18 -  12:18 UT, I get the error message that (e.g.)
"No AIA 335 data is available on or after 2023-09-29T11:18:09Z."

But there are AIA data available for that day and time range. 

Thanks.

**Comment by ebuchlin** [comment]
2023-09-29 is in the future, are you sure that the date is correct? And which HelioViewer server are you using?

**Comment by averonig** [comment]
Sorry, I meant 2022-09-29, and the usage of JHelioviewer.

I use the JHelioviewer on the mac, and downloaded the latest version. Ludwig Klein independently had the same issue with this event/date.

Thanks!
Astrid

---
Univ.-Prof. Dr. Astrid Veronig
Professor of Solar and Heliospheric Physics
Head of Kanzelhöhe Observatory for Solar and Environmental Research
Institute of Physics, University of Graz, Universitätsplatz 5, 8010 Graz
Faculty of Natural Sciences, Vice-Dean of Research
Tel: +43 (0) 316 380 8609
Email: ***@***.******@***.***>



Von: ebuchlin ***@***.***>
Antworten an: Helioviewer-Project/JHelioviewer-SWHV ***@***.***>
Datum: Montag, 12. Juni 2023 um 19:05
An: Helioviewer-Project/JHelioviewer-SWHV ***@***.***>
Cc: "Veronig, Astrid ***@***.***)" ***@***.***>, Author ***@***.***>
Betreff: Re: [Helioviewer-Project/JHelioviewer-SWHV] No AIA data avilabe error message although there exist data (Issue #244)


2023-09-29 is in the future, are you sure that the date is correct? And which HelioViewer server are you using?

**Comment by ebuchlin** [comment]
I confirm that using the IAS/MEDOC server, I get  "Error encountered during JPX creation: Error creating JPX file (...)", which could be due to corrupted files (see in [this issue](https://github.com/Helioviewer-Project/api/issues/293#issuecomment-1540533331); we are replacing the files but it takes time)

**Comment by ebuchlin** [comment]
But with GSFC AIA 335 I get "java.util.concurrent.CompletionException: java.io.IOException: Could not parse jpips://helioviewer.org:8090/movies/SDO_AIA_335_F2022-09-29T00.00.00Z_T2022-09-30T00.00.00ZB900L.jpx"

**Comment by bogdanni** [comment]
Please use release [4.5.0](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/releases/tag/4.5.0) for:
> Capability for SSL connection to JPIP movie streaming server, required for GSFC server

**Comment by ebuchlin** [comment]
Now GSFC works for be for AIA 304, 2022-09-29T11:18 to T12:18.

![image](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/3624676/1b37fa17-69c7-475a-9165-159f7bdfde1d)

I still get the Kakadu error (because of corrupted files) on our server. We are now replacing the SDO files month per month, to better monitor progress.

**Comment by bogdanni** [comment]
Dear Astrid,
I'm not sure how you try to load data from different servers, but, if you select menu File -> New Image Layer, you will get a window like below in which the datasets are presented as trees rooted in the names of the servers. You have to select the tree with name GSFC. The presentation is identical in the popup from the New Layer button (it's just easier for me to take the screenshot from the window)

![image](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/1223825/bfc2a5c8-d31c-4fb7-b827-f8f65ca1175d)

**Comment by averonig** [comment]
Dear Bogdan, dear Eric,

Now it works for me with the data from the NASA server.
Thanks a lot for your help!

Astrid






Von: Bogdan Nicula ***@***.***>
Antworten an: Helioviewer-Project/JHelioviewer-SWHV ***@***.***>
Datum: Freitag, 16. Juni 2023 um 07:43
An: Helioviewer-Project/JHelioviewer-SWHV ***@***.***>
Cc: "Veronig, Astrid ***@***.***)" ***@***.***>, Author ***@***.***>
Betreff: Re: [Helioviewer-Project/JHelioviewer-SWHV] No AIA data avilabe error message although there exist data (Issue #244)


Dear Astrid,
I'm not sure how you try to load data from different servers, but, if you select menu File -> New Image Layer, you will get a window like below in which the datasets are presented as trees rooted in the names of the servers. You have to select the tree with name GSFC. The presentation is identical in the popup from the New Layer button (it's just easier for me to take the screenshot from the window)

[image]<https://user-images.githubusercontent.com/1223825/246325852-bfc2a5c8-d31c-4fb7-b827-f8f65ca1175d.png>

**Comment by bogdanni** [comment]
Closing this. The IAS server will eventually catch up with repairing the corrupted files.
