### ISSUE TITLE
Error from GSFC,IAS, ROB and there is no data for many days

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/JHelioviewer-SWHV#245]
when i select GSFC-SDO (and SUVI) it's giving this error: java.util.concurrent.CompletionException: java.io.IOException: Could not parse jpips://helioviewer.org:8090/movies/SDO_AIA_304_F2023-07-11T06.18.09Z_T2023-07-13T06.18.09ZB1800L.jpx

even with the latest update
same from IAS (sdo) and ROB. why?

**Comment by bogdanni** [comment]
Could you please give more details, cannot reproduce. Are you using version 4.5.1?

**Comment by Anthrwpos** [comment]
More details like? Yes latest version. Why is this error?



________________________________

**Comment by bogdanni** [comment]
Cannot reproduce.
