### ISSUE TITLE
My own and shareable statistical, analysis and machine vision algorithms

### ISSUE THREAD

**Issue by RichardKCollins** [Helioviewer-Project/JHelioviewer-SWHV#250]
I only found JHelioviewer today.  I downloaded quite a few FITS files the last few years, many of the sun. But I also have NetCDF, ASDF, CDF, HDF, Tiff, J2000 and other formats.  I can load and display images, and play with them.  The color scheme is hard on old eyes but I can get a few things to work.  

I read a bit about SAMP and it sounds like some experiments I did for the Internet Foundation on sharing.  I try to set standards for global open formats for all Internet content.

This is Java based.  I have used Fortran, Algol, Assembler, VB.net, C, C++, Pascal, Javascript, Python and have a reading knowledge of most all languages since a standard for sharing algorithms is a high priority since there are about 5 billion people now with some access to the Internet. The only common language is Javascript. The developers and programmers are a different species, I treat them different (joke).

I would like to add a "edit debug run schedule" buttons to this interface, or run headless.

When I was installing in Windows (an old Win 7 pro), it asked for permission to access the Internet, and I did not allow that by pure reflex.  But I cannot load images from the servers.  I tried several servers (if the settings selection of server is what I think it might be) and all of them fail.

I did load some jpegs of SDO images I have been studying.  I am trying to see if I can tweak the jpeg and mpeg compression pipelines to encode real data and be able to recover it.  I have been trying for several years to get all the astrophysics, solar, geophysics and global sensor networks to use lossless formats.  I bugged NASA and ESA and others where the put "pretty pictures and movies" online and they ought to put lossless data - machine vision, statistics, patterns, correlations, principled archiving and sharing.  That sort of thing.

I do not have a Java development tool.  I have used Visual Studio a bit.  But accumulating and mastering toolkits and IDEs that few of the 8 billion people now can afford is not something I should do.  I wrote a lots of content scripts in javascript Chrome browser.  I use that routinely with IIS localhost and jscripts I wrote to access the computer.  That allows a content script to read and write files, scan directories, access the Internet, block read and write, access databases. I tried NodeJs http server and that works. 

But right now I would like some way to access the pixels and metadata from images loaded in JHelioviewer, to run srcripts to download and process images, share data between processes, share open data on the Internet.  I do have stuff on GitHub. I downloaded and analyzed about 200 of the largest projects on Github.  For the Internet Foundation, I am trying to set standards for sharing : Symbolic mathematics particularly whole models like stellar models, atmospheric models.  Computer logic in open accessible formats combining and merging algorithms regardless of source language.  (My brother is doing a lot of that, I think he is up to 34 languages now).

I studied statistical mechanics, quantum chemistry, astrophysics, and gravitational wave detection at UT Austin and UMD College Park.  But I also worked on gravitational potential models and gravimeter imaging arrays.  I trace most of the global sensor networks - gravimeters, seismometers, magnetometers, infrasound, electric, electromagnetic, neutrino and other networks. There is a lot going on on the Internet, and I tried for the last 25 years of the Internet Foundation to document and write policies and methods that best encourage global sharing and collaboration.

I apologize for writing so much.  I am just trying to introduce myself and I have been working on some of these things every day for the last 30 years, and I had a full career before that in international development, climate change, alternative fuels and mostly "global issues and opportunities".  

But I have only downloaded JHelioviewer to try it, and the source code to read what you are doing. But  I do not have any tools to use Java, and I would rather start by adding buttons or lists and "run this on these images and put the results here".  I want to look at differential rotation on the sun.  I am also working on global climate change groups.  "climate change" has 1.24 Billion entry points on the Internet, and most of the groups are doing their own thing.  They might "collaborate" within their small communities ( a few millions is "small") but the larger islands of groups are all hanging tight to their old formats, programs, languages and methods.  So things take decades or longer, when an open system would be minutes days weeks.

Richard Collins, The Internet Foundation

**Comment by bogdanni** [comment]
Off-topic.
