### ISSUE TITLE
java.net.ConnectException: Connection timed out: no further information:

### ISSUE THREAD

**Issue by 1402595068** [Helioviewer-Project/JHelioviewer-SWHV#252]
java.net.ConnectException: Connection timed out: no further information: jpip://helioviewer.ias.u-psud.fr:8080//movies/SDO_AIA_171_F2023-09-18T13.46.57Z_T2023-09-20T13.46.57ZB1800L.jpx
![image](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145579506/c25572e6-6539-4b61-a91b-f4e524523487)

**Comment by ebuchlin** [comment]
Hello, JHelioViewer is working on my side, could you please give more context, [as explained in the README](https://github.com/Helioviewer-Project/JHelioviewer-SWHV#report-a-problem-or-idea)?

**Comment by 1402595068** [comment]
java.net.ConnectException: Connection timed out: no further information: jpip://helioviewer.ias.u-psud.fr:8080//movies/SDO_AIA_171_F2023-09-18T14.48.09Z_T2023-09-20T14.48.09ZB1800L.jpx

**Comment by bogdanni** [comment]
Are you behind a strict firewall which blocks traffic on "unusual" ports?
For the IAS server, JHV has to communicate on port 8080.

**Comment by 1402595068** [comment]
excuse me ,i had close my firewall,and then how can i change the port to 8080 in this softwore？

**Comment by bogdanni** [comment]
The port which is used for streaming movies is dictated by the server, you cannot change it from the JHV side.
You mentioned that it worked one day, then it didn't. Maybe you moved the computer between networks if this is a laptop. Some institutions have very strict firewalls which block any ports which are not related to web browsing.

**Comment by 1402595068** [comment]
but other people could use JHV under the same wifi.i change the internet but also could not work.i doubt there is something wrong with my computer setting

**Comment by 1402595068** [comment]
![image](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145579506/88c6da94-b7e3-4562-ae08-fff19964089f)
![QQ图片20230922110313](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145579506/d95ef9eb-14ec-4dab-a17e-4b4d79928534)



this is my port setting .what should i change ？

**Comment by bogdanni** [comment]
User runs local firewall software which blocks JHV networking.
