### ISSUE TITLE
Wireframe showing up in movies on Frame 2 onwards...

### ISSUE THREAD

**Issue by Cr0under** [Helioviewer-Project/JHelioviewer-SWHV#253]
Hi everyone,

Firstly congratulations on an absolutely brilliant piece of software. I am having such fun with it!

I am an independent filmmaker crafting a non-commercial Sci-Fi movie. I would like to use JHV to generate some shots for said movie. Unfortunately, I've discovered a bug that is hampering my exported movies from JHV.

When I load an image sequence from SDO (say AIA 304), and use my trackpad/keyboard shortcuts and Pan controls to Zoom into an area of interest such as the curvature of the sun, all is good. If I use the Movie Controls to advance a frame, I now see the faint but stark wireframe border between the body of the sun and the Corona (if Corona is turned on). If you go back to frame 1, this wireframe disappears.

Unfortunately this same wireframe shows up in my exported sequences (H264/PNG), which makes those images unusable (at least for my purposes). Please see attached screengrab.

Please let me know if this can be reproduced.

thank you,

milton

PS iMac 2017 MacOS Catalina 10.15.7 Radeon Pro 580 8GB

![Screen Shot 2023-09-20 at 9 51 17 AM](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145597495/c66f7a16-c670-43a3-aa4e-04e44e1f0a1a)

**Comment by bogdanni** [comment]
Wow, that must the coolest ever use of JHV.

I cannot reproduce this. 
- Could you please try with only one layer fully loaded?
- If you have access to another (newer) computer, could you please try it also there? To me it looks that either the OpenGL hardware or software doesn't have the full capabilities for this rendering.

**Comment by Cr0under** [comment]
Thanks Bogdanni,

I actually figured it out. Well, I installed JHV on an old Mac Pro 5,1 running Monterey and a Radeon Vega 64 GPU and the problem seemed to go away :)

I'm attaching some stills so you can see what I'm using JHV for. Creative a lot of 'creative license' here, but the software is simply amazing in what it allows you to achieve! I can't thank the developers enough :)

Thanks!

![Sun_02_8 1 1](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145597495/c8ce8092-2f6d-4f16-9378-20624baac734)
![Sun_03_6 1 1](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145597495/2b87121b-f590-4308-9340-87cebb4f6202)
![Sun_04_4 1 1](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/145597495/57c65e8d-6fe0-47a4-9a40-be3b2f9a0ff3)

**Comment by bogdanni** [comment]
Yes, I suspect it's the combination of the versions of OpenGL driver and hardware which makes for that rendering artefact.

Your results are gorgeous and you are an expert user. The "creative license" is part of your artistry and it's Sci-Fi afterall!
Please let us know when you publish your work to check it out.

**Comment by Cr0under** [comment]
Thanks for your kind words Bogdanni. I'll let you know when this is out :)

**Comment by bogdanni** [comment]
Most likely an OpenGL driver issue.
