### ISSUE TITLE
Downloading more than 97 frames at a time...

### ISSUE THREAD

**Issue by Cr0under** [Helioviewer-Project/JHelioviewer-SWHV#254]
Hi guys,

I've been using JHV this week and I'd like to know if there's any way of increasing the downloaded frames beyond 97 (@ 30 min cadence). I am aware that changing the cadence in one direction does afford more frames, but I'd like to be able to do this by default as 96 frames only amounts to 4 seconds @ 24fps. I've tried downloading 'the next batch' of 97 frames by aligning the IN/OUT time, but this is so error prone (correction: I'm so error prone!) that I keep ending up with misaligned animation.

I'm working with some sequences that I'm really digging, but having 50% more total run time (TRT) or even 100% more (8 seconds!!) would be amazing!

Thanks all in advance.

milton

**Comment by bogdanni** [comment]
Please use menu File->New Image Layer. That allows to set the cadence (time step). Maximum frames will be ~1000.
The button sets the cadence for ~97 frames to avoid naive users swamping the servers (1 AIA full frame is about 1MB).

**Comment by Cr0under** [comment]
Perfect. Thanks!
