### ISSUE TITLE
Exporting AIA movies as a series of images

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer-SWHV#26]
A user has requested the ability to export movies of AIA data as a series of individual 4k by 4k image frames.  The user requested this ability for AIA images only.  The reason for this is that the user wants to be able to manipulate the images individually, and to create movies using these images using their own movie creation tools.  A related feature request has been logged at https://github.com/Helioviewer-Project/helioviewer.org/issues/180.

**Comment by bogdanni** [comment]
We are going to implement something different, output in Apple ProRes format. This sophisticated user will know what to do with that.

**Comment by bogdanni** [comment]
Note that the movies currently output by JHV have only I-frames, so it's possible that they can be split into individual frames with little loss of quality. The re-encode after editing however may lead to quality loss.
