### ISSUE TITLE
Possible improvement of user interaction?

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#261]
Use case: I want to plot S/C trajectories for an extended period in the future. 
Issue: When I try to set the start date with the date picker, nothing happens; when I try the same by typing into the start date field, the date is reset to the end date upon hitting return.
Reason: JHV rightly does not accept a start date that is later than the end date. However, this can be confusing to the user who will usually fill in the start date first.
Possible solution: Adding a "go" button would be an option (similar to the 'sync' button for the master time selector). Alternatively, one could add a pop-up "end time must be after start time" but some users might still complain that having to enter the end time first feels counter-intuitive.

**Comment by bogdanni** [comment]
I would like to avoid extra UI elements.
You are right that people think first of start and second of end for intervals. The code was changed to auto adjust the end to be at least as late as the start. This should eliminate 99% of possible confusing behaviour.

It seemed more intuitive the other way around when this was implemented, but I don't think normally :)
Hopefully it will not annoy too much the users who already trained themselves.
