### ISSUE TITLE
Colors won't change correctly / Version 4.6.0.10927

### ISSUE THREAD

**Issue by sflorg** [Helioviewer-Project/JHelioviewer-SWHV#263]
The color stays on the previous one selected unless you change to another and then go back.
Opening more than one image is impossible to do correctly. I have never seen this issue before and use the program daily.
Where can I download the previous EXE.
![2024-02-08_093245](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/60510691/f844263d-8d66-459a-8555-6453f0665dcb)
![2024-02-08_093206](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/assets/60510691/db6035c5-108d-4ad5-889d-7cabbc7d9c0b)

**Comment by bogdanni** [comment]
Confirmed and sorry for that :(, nothing should have changed in this area.
You can download 4.5.5 from https://swhv.oma.be/download/old/

I will try to fix this asap.

**Comment by sflorg** [comment]
Life happens, thanks you.
Heidi-Ann

**Comment by bogdanni** [comment]
Released 4.6.1 with the fix.
