### ISSUE TITLE
How to install (wrong instructions)?

### ISSUE THREAD

**Issue by eabase** [Helioviewer-Project/JHelioviewer-SWHV#266]
How do you install this application?

I'm looking at the installation instructions from [here](https://swhv.oma.be/user_manual/) and those instructions are either wrong or seriously outdated. I am not able to run the sources with Java JDK installation. (See #265 )

Please update both the README and the documentation!

**Comment by bogdanni** [comment]
The installation instructions say to use the exe installer: https://swhv.oma.be/user_manual/#windows
