### ISSUE TITLE
Having issues when I load a new layer/Mac

### ISSUE THREAD

**Issue by capa008** [Helioviewer-Project/JHelioviewer-SWHV#278]
I have this problem, btw this is my first time using Helioviewer, thanks for your support:

java.util.concurrent.CompletionException: java.io.IOException: Could not parse jpips://helioviewer.org:8090/movies/STEREO_A_SECCHI_EUVI_171_F2019-10-10T05.00.00Z_T2019-10-10T15.00.00ZB375L.jpx

**Comment by bogdanni** [comment]
I tried that and worked for me. Could you please try another instrument and/or time range? Maybe it was a transient server issue.

**Comment by bogdanni** [comment]
Most likely a transient server error: please file a new report if you encounter further difficulties.
