### ISSUE TITLE
The start and end date_time is not restored after "Load State"

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#281]
Version: 4.7.0.11268 on Ubuntu 22.04.

File -> Load State, the time ranges of image data are restored as expected, but the Start and End Date-Time in the input boxes below the "Options" button are not restored.

**Comment by bogdanni** [comment]
Start-end times are not part of state.

**Comment by GitatHub** [comment]
> Start-end times are not part of state.

I think they could be part of state. IMHO, when we restore from a state to continue the work, we do not want to manually set the time ranges again.

**Comment by ebuchlin** [comment]
Maybe there could be an option to choose to include or exclude the times from the state? In the state file they could be filled or empty. If filled, they are taken into account, if empty we're back to the current behaviour. Would this seem reasonable?

**Comment by GitatHub** [comment]
> Maybe there could be an option to choose to include or exclude the times from the state? In the state file they could be filled or empty. If filled, they are taken into account, if empty we're back to the current behaviour. Would this seem reasonable?

Sounds like a good idea, if @bogdanni Bogdan does not mind the workload of adding an new option...
