### ISSUE TITLE
Why can't I get more image files?

### ISSUE THREAD

**Issue by Saparonia** [Helioviewer-Project/JHelioviewer-SWHV#37]
I used to get all the SDO image files from AIA but now I only get SDO AIA 305 and 171, (and HMI that I don't normally use). It says I'm using the latest version, also I'm on Linux

**Comment by bogdanni** [comment]
Please use the GSFC or IAS server. You can also set the default highlighted server in Preferences.

**Comment by Saparonia** [comment]
thank you !!
