### ISSUE TITLE
Movie Notification

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/JHelioviewer-SWHV#38]
A user has reported missing the sliding growl notification at the top right of the screen.  It may be because she was working on multiple screens, or looked away from her screens and so missed the notification.

A solution to this would be to have a notification appear in the JHelioviewer window that the user has to deliberately click on to remove.

**Comment by bogdanni** [comment]
That notification is Mac native and behaves like Mac notifications. It can retrieved later via the Notification Center, including the link to the exported file.
