### ISSUE TITLE
GOES XRS data

### ISSUE THREAD

**Issue by larrymanley** [Helioviewer-Project/JHelioviewer-SWHV#39]
No data is displayed prior to 2013-05-09.  The "STAFF" source is OK though.

**Comment by bogdanni** [comment]
That's right, that's JHV's home brewed source, data essentially starts when someone started importing it. "STAFF" is derived from http://www.staff.oma.be .

**Comment by bogdanni** [comment]
STAFF is now the default and the only source for GOES XRS.
