### ISSUE TITLE
Save/Load State

### ISSUE THREAD

**Issue by gor1111** [Helioviewer-Project/JHelioviewer-SWHV#40]
The new version surprisingly has no so useful feature **Save/Load State**. When a lot of layers are needed to be analyzed, it is so time consuming to recover them again and again.

Please add that.
Thank you in advance!

With best wishes.
AG

**Comment by bogdanni** [comment]
It will actually be in the next release. You can have a sneak peek with a build from http://swhv.oma.be/download_test/ . Please see in the File menu. No guarantees.

**Comment by gor1111** [comment]
Thanks!

**Comment by bogdanni** [comment]
This will be in JHV 2.12.
