### ISSUE TITLE
Use cached files when extending time range

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#42]
If it possible to use the cached files previously downloaded after I extend the time range of data?
e.g., I viewed images from 1000 to 1400 and I then extend the time range to 0800 to 1600.
Currently JHV will redownload those data between 1000 and 1400 after I change the time range -- this will consume some time and may increase the work load of the server. If it possible to check cached data before downloading them?

another suggestion, could it be possible to set the font size of the time stamp? e.g., enlarge the text.

Thanks.

**Comment by bogdanni** [comment]
Thank you for the suggestions. Both are on the to-do list.

**Comment by bogdanni** [comment]
Capability to set timestamp font size will be in JHV 2.12.

**Comment by bogdanni** [comment]
Image data caching will be in JHV 2.12.3.
