### ISSUE TITLE
Two feature suggestions

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#44]
1. automatically change the end time of data after user have set the start time. 
e.g., after the user input the start time as 2017-01-01 02:23:34, the application will automatically set the end time to be like 2017-01-02 02:23:34 but not the default one 2017-09-08 3:3:3

2. is it possible to change the format of saved movie? currently the default format of movie is MP4 which is not supported (cannot be played) by Office 2013 PowerPoint in Windows. 
I found that AVI format can be played within PowerPoint 2013 and widely supported by other applications.
The application imagej supports saving movies as AVI, and is it possible to implement the same feature in JHelioviewer? 

Thanks.

**Comment by bogdanni** [comment]
Thank you for the suggestions.
1. There are many useful cases in which the length of time interval should be left to the user to fill in.
2. The movie format is an ISO/ITU standard (H.264 in MP4 file) supported by many computer platforms. It is possible to transcode to some other desired format, even using online services.

**Comment by ZexaronS** [comment]
@GitatHub Microsoft article states that PowerPoint 2013 is able to play MP4, M4V, MOV, and even PowerPoint 2010 if Quicktime is installed. You may be look further investigating the issue by contacting Office support, as well as trying other MP4 files to see if PowerPoint 2013 only has a problem with the ones coming from JHelioviewer.

@bogdanni 
I think he was asking for an additonal optional option, why cannot the existing behavior be kept as a default while his suggestion implemented as a bool setting?

**Comment by GitatHub** [comment]
@ZexaronS Office 2013 only supports H.264 coded MP4 but not QT format MP4 (see https://support.office.com/en-us/article/Video-and-audio-file-formats-supported-in-PowerPoint-d8b12450-26db-4c7b-a5c1-593d3418fb59).
I used command 
> file 
 in Linux and found that the format of MP4 created by JHV is in QuikcPlay format (?)
And I indeed find that PowerPoint can play other MP4 vidoes but not JHV created ones.
for example, you can download MP4 files from http://www.clipconverter.cc/ and play it inside PowerPoint 2013. 
I tried to install QT to solve this, but it seems that PPT 2013 does not call QT anymore.

@bogdanni  As to the data time, I can understand that there are different requests for different users.
However, if it is better to automatically change the end time from 2017-09-08 to 2012-03-03 when I have input the start time as 2012-03-02? it will be more convenient because the user do not need to change the year. If the application could auto change the end time of data when the default end time is (e.g.,) three days from the input start time, in my humble opinion, it will more user friendly. I admit that this request is of low priority. thanks for your work.

**Comment by bogdanni** [comment]
@GitatHub The MP4 files are optimized for (web) streaming. On my computer they are recognized by ```file``` as ```ISO Media, Apple QuickTime movie, Apple QuickTime (.MOV/QT)```. Non-optimized files are seen as ```ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]```.

Could you please test in your PPT 2013 if the file at 
http://swhv.oma.be/test/JHV_2017-09-08_16.31.33.mp4
works?

**Comment by GitatHub** [comment]
@bogdanni  
The test MP4 from your link does not work inside my PowerPoint 2013 in Windows 10 X64.
I converted it manually to a new MP4 file and it can then be played in PPT 2013.

**Your test file info:**
`General
Complete name                  : JHV_2017-09-08_16.31.33.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom
File size                      : 4.46 MiB
Duration                       : 4s 800ms
Overall bit rate mode          : Variable
Overall bit rate               : 7 797 Kbps
Encoded date                   : UTC 2017-09-08 16:31:41
Tagged date                    : UTC 2017-09-08 16:31:41
Writing library                : Apple QuickTime

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Baseline@L4
Format settings, CABAC         : No
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 4s 800ms
Bit rate mode                  : Variable
Bit rate                       : 7 794 Kbps
Width                          : 968 pixels
Height                         : 680 pixels
Display aspect ratio           : 1.424
Frame rate mode                : Constant
Frame rate                     : 20.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.592
Stream size                    : 4.46 MiB (100%)
Language                       : English
Encoded date                   : UTC 2017-09-08 16:31:41
Tagged date                    : UTC 2017-09-08 16:31:41`


**My converted file:**
`General
Complete name                  : Convert-JHV_2017-09-08_16.31.33.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom
File size                      : 1.04 MiB
Duration                       : 4s 800ms
Overall bit rate mode          : Constant
Overall bit rate               : 1 818 Kbps
Writing application            : Lavf57.41.100

Video
ID                             : 1
Format                         : MPEG-4 Visual
Format profile                 : Simple@L1
Format settings, BVOP          : No
Format settings, QPel          : No
Format settings, GMC           : No warppoints
Format settings, Matrix        : Default (H.263)
Codec ID                       : 20
Duration                       : 4s 800ms
Bit rate mode                  : Constant
Bit rate                       : 1 815 Kbps
Width                          : 1 024 pixels
Height                         : 680 pixels
Display aspect ratio           : 3:2
Frame rate mode                : Constant
Frame rate                     : 20.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.130
Stream size                    : 1.04 MiB (100%)
Writing library                : Lavc57.48.101
Language                       : English `

**Comment by bogdanni** [comment]
@GitatHub You converted to the MPEG-4 codec.
You are even running Windows 10 which natively supports H.264. That webpage even says: "In PowerPoint 2013 and later, ..., for the best video playback experience, we recommend that you use .mp4 files encoded with H.264 video (a.k.a. MPEG-4 AVC) and AAC audio."

**Comment by bogdanni** [comment]
@GitatHub What symptoms do you see? Does it complain about unknown codec?

In my test, the movies can be inserted into PPT2013. On the other hand, both Windows movie player and PPT show just a couple of frames from a default ~5s video. There may be a problem with the video coding library we use. Leaving this open.

**Comment by GitatHub** [comment]
@bogdanni I did not see any error information output. 
The JHV MP4 video just shows as a black frame when being played.

**Comment by bogdanni** [comment]
So it is recognized, it's a playback problem.

Could you please try this one:
http://swhv.oma.be/test/JHV_2017-08-21_08.59.03-jcodec-0.2.0.mp4

**Comment by ZexaronS** [comment]
@GitatHub If you can provide the samples of the working and non-working cases, I might be able to help by using ffprobe or a more in-depth tool to see what the difference is.

**Comment by GitatHub** [comment]
@bogdanni  Thanks for your sample file. The movie your provided at http://swhv.oma.be/test/JHV_2017-08-21_08.59.03-jcodec-0.2.0.mp4 is working in PPT 2013 in WIN 10.

@ZexaronS Thanks for your reply. And you may see the working file from bogdanni. 
non-working ones can be directly got from JHV of current release (in Fedora 26 with JRE 1.8+ if I should provide these).

**Comment by bogdanni** [comment]
Solved as part #45 .
