### ISSUE TITLE
Error Message when trying to load HMI magnetograms from ROB server

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#46]
HMI continuum images from ROB worked fine, as well as HMI magnetograms from GSFC.

<img width="4208" alt="screen shot 2017-09-25 at 10 37 28" src="https://user-images.githubusercontent.com/9073862/30799667-ef1651a4-a1dd-11e7-9829-b15b1b74e11c.png">

Thank you!

**Comment by bogdanni** [comment]
This is most likely due to an issue between the ROB server virtual machine and the virtual storage and computing infrastructure at ROB. Hopefully fixed by migrating to the new ROB server virtual machine.

**Comment by bogdanni** [comment]
This should be now mitigated on the ROB server.
