### ISSUE TITLE
Data problem

### ISSUE THREAD

**Issue by nechaeva** [Helioviewer-Project/JHelioviewer-SWHV#47]
Hello,
I have recently discovered that data from IAS is not available at all. And when using SDO AIA 171 Å data I can't set timestep I want,  the smallest timestep I get is usually about 5 mins.

![hvbug](https://user-images.githubusercontent.com/25328330/30900072-31412f0c-a36b-11e7-883a-26e5b2ca2ba2.png)

Thank you in advance.

**Comment by bogdanni** [comment]
- The IAS server is currently being upgraded and is unavailable.
- The ROB server contains a subset of SDO data.
- For access to GSFC server, please upgrade Java to the version 8 latest update (144).
