### ISSUE TITLE
Not all Active Regions being displayed?

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/JHelioviewer-SWHV#5]
Loaded image data from 29 March 2016. A big sunspot is present on the visible hemisphere (AR 2526), but is neither marked in the image panel nor visible in timeline. However, it is listed on http://www.lmsal.com/solarsoft/latest_events/ and helioviewer.org.

**Comment by dmueller3000** [comment]
It turned out that in the (hidden) Data Sources panel, all images/layer settings of the single layer (I believe ~5 !) were set to "SOHO". When I changed this to something else (incl. later back to 'SOHO), it worked.

**Comment by bogdanni** [comment]
For the record, this is the HEK link:
[https://www.lmsal.com/isolsearch?hek_query=https://www.lmsal.com/hek/her?cosec=2&&cmd=search&type=column&event_type=ss&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2016-03-29T00:00:00&event_endtime=2016-03-29T23:59:59](url)

Note that the sunspots in HEK are the result of a feature finding algorithm.
Is this a bug?

**Comment by bogdanni** [comment]
Confirmed, this seems to be MIA:
[http://www.lmsal.com/hek/her?cmd=export-voevent&cosec=1&ivorn=ivo%3A%2F%2Fhelio-informatics.org%2FAR_NOAASWPCObserver_20160329_023531_NOAA12526_20160329](url)

**Comment by bogdanni** [comment]
Fixed (r6811)
