### ISSUE TITLE
[AWT-EventQueue-0] FATAL root - Runtime exception

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#51]
see https://github.com/Helioviewer-Project/JHelioviewer/issues/300 
for details.

**Comment by bogdanni** [comment]
See https://stackoverflow.com/a/39963840

**Comment by GitatHub** [comment]
@bogdanni 
sudo yum install java-1.8.0-openjdk
Last metadata expiration check: 2:05:55 ago on Sat 25 Nov 2017 11:13:38 PM CST.
Package java-1.8.0-openjdk-1:1.8.0.151-1.b12.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

sudo yum install java-1.8.0-openjdk-headless
Last metadata expiration check: 2:06:05 ago on Sat 25 Nov 2017 11:13:38 PM CST.
Package java-1.8.0-openjdk-headless-1:1.8.0.151-1.b12.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

java -D java.awt.headless=false
Error: Could not find or load main class java.awt.headless=false

java -D java.awt.headless=true
Error: Could not find or load main class java.awt.headless=false

So the stackoverflow solution might not be the solution here.

**Comment by bogdanni** [comment]
No space between -D and  java.awt.headless=true
This program is supported only under the official Java.

**Comment by bogdanni** [comment]
For the record, the entire command line:
`java -Djava.awt.headless=false -jar JHelioviewer.jar`
