### ISSUE TITLE
https://api.helioviewer.org CERT out of date

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#54]
JHVWorker-MAIN--DataSources] WARN  root - HTTP connection failed: https://api.helioviewer.org/v2/getDataSources/?verbose=true&enable=[TRACE,Hinode,Yohkoh,STEREO_A,STEREO_B,PROBA2] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by bogdanni** [comment]
Has to be fixed server side by updating the SSL certificate.
