### ISSUE TITLE
Heliocentric coordinates are missing in JHelioviewer 2.10

### ISSUE THREAD

**Issue by pryoung** [Helioviewer-Project/JHelioviewer-SWHV#6]
Hello,

The old JHelioviewer was a very useful tool when planning observations for IRIS and Hinode as I could get a latest image, point with the mouse on a feature, and get the coordinates of that feature in the bottom-right corner of the GUI in heliocentric coordinates. I could then send the coordinates to the instrument planner.

With the new 2.10 version, the coordinates have been changed to 3D spherical coordinates which are no good for me. Please can you go back to the old coordinates, or at least give an option.

Thanks,  Peter.

**Comment by mablesly** [comment]
Dear Peter,

You can select the grid in the image layers panel. There is an option panel for grid appearing at the bottom of the image layers panel where you can select the grid type. By selecting HCI the position of the mouse will be given in HCI. 

I hope this is what you wanted?

Best regards, 

Bram

**Comment by pryoung** [comment]
Hi Bram,

Thanks for this. I tried HCI and it added a large cross to the image, but the coordinates are still given in phi, theta and rho. (I notice the grid still seems to be showing longitude and latitude with HCI). I just want X and Y relative to Sun center.

Regards,

Peter

**Comment by bogdanni** [comment]
The heliocentric (I believe better named helioprojective) indicator was re-introduced. The caveats being that it's dependent on observer position (or viewpoint in JHV nomenclature) and any rotation away from the observer projection invalidates it.
