### ISSUE TITLE
Error message when opening JHelioViewer

### ISSUE THREAD

**Issue by Maettu67** [Helioviewer-Project/JHelioviewer-SWHV#60]
Recently, almost every time I open JHV, I get an error message and no data:
"An error occured while opening the remote file: 
Error opening HTTP connection to https://api.helioviewer.org/v2/getJPX/?sourceid=10&startTime= (...) &cadence=1800&jpip=true&verbose=true&linked=true Response code: 500"
I'm not a programmer and not familiar with this code. I searched this site for this problem/ error code, and it appears to me that noone seems to have brought up this issue before. 
Thanks for assistance!
![bildschirmfoto 2018-02-07 um 15 18 17](https://user-images.githubusercontent.com/36234083/35921603-6810afd0-0c1b-11e8-9203-35090d283dbd.png)

**Comment by bogdanni** [comment]
This is a malfunction of the GSFC server. I hoped this would be solved soon after your report, but has not.
Please use the IAS server. You can also set it as default in Preferences.
