### ISSUE TITLE
Trouble downloading data from ROB and GSFC

### ISSUE THREAD

**Issue by takucera** [Helioviewer-Project/JHelioviewer-SWHV#61]
I am getting the errors when trying to download data, both from ROB and GSFC, although the text is different. I am trying to attach the error windows, although I am not sure it is working.

The GSFC ones starts with "An error occurred while opening the remote file: Error opening HTTP connection to.....
 The ROB one starts with 
"Error getting the data  
Error encountered during JPX creation..."

![error_rob](https://user-images.githubusercontent.com/31491127/35937127-43e4ccde-0c13-11e8-81e0-8bc57e91231e.jpg)
![error_gsfc](https://user-images.githubusercontent.com/31491127/35937129-44214376-0c13-11e8-8ce5-9902fef4203f.jpg)

**Comment by bogdanni** [comment]
This is a malfunction of the GSFC server. The issue on the ROB server is now mitigated.
For the widest data coverage, please use the IAS server. You can also set it as default in Preferences.
