### ISSUE TITLE
Cannot download LASCO data 

### ISSUE THREAD

**Issue by ManuelaTemmer** [Helioviewer-Project/JHelioviewer-SWHV#62]
LASCO data download not possible.

**Comment by bogdanni** [comment]
Should be possible from IAS server.
ROB server has minimal datasets.

**Comment by ManuelaTemmer** [comment]
thanks for the fast response, however, IAS, GSFC - both not working, though data are available when using helioviewer.org

**Comment by bogdanni** [comment]
Are you looking for a particular date range in 2017 or 2016? The IAS server has indeed some LASCO gaps.

Or is IAS server not working at all for you? If so, are you using version 2.12.0?
GSFC server currently malfunctions.

**Comment by ManuelaTemmer** [comment]
I am in particular looking for July 23, 2017 - which works fine on helioviewer.org. Also other dates are working on helioviewer.org, but not under Jhelioviewer. And yes, I use Version 2.12.0.8493

**Comment by bogdanni** [comment]
Unfortunately, the IAS server has a gap for LASCO between Sep 2016 and Sep 2017. They were notified.

I've put manually made movies with all LASCO frames available for Jul 22-24 2017 at
http://nicula.net/lasco/
You can download them with the web browser and then open in JHV via File->Open Image Layer. Use shift key when selecting to open both at the same time.

**Comment by bogdanni** [comment]
The LASCO data should be now complete on the IAS server.
This was a known problem for a while, but coincidentally our IAS colleagues could solve it today.
