### ISSUE TITLE
Error occured when trying to access STEREO data.

### ISSUE THREAD

**Issue by takucera** [Helioviewer-Project/JHelioviewer-SWHV#68]
Hi,
I am getting the attached error message when trying to download STEREO/EUVI data from GSFC. i think I have also gotten it before trying to download it from IAS. I don't get it for all STEREO/EUVI data data. The data I am trying to get at the moment is from EUVI-A, 2014-Apr-7, 195 A
An error occurred while opening the remote file: org.helioviewer.jhv.view.jp2view.kakadu.JHV_KduException: Error in server communication: invalid HTTP response: HTTP/1.1 500 Internal Service Error

![jhelioviewer_error](https://user-images.githubusercontent.com/31491127/39816392-27fb33f8-5369-11e8-82b6-2ccf0f5f0c76.jpeg)

**Comment by bogdanni** [comment]
This error usually signifies a server side issue.

Loading EUVI-A 195 from IAS works here currently for the period 2014-04-07 till 2014-04-09.
GSFC server times out or resets connection.

**Comment by wafels** [comment]
Trying some other times and instruments also results in timeouts...
helioviewer.org is running OK.

**Comment by wafels** [comment]
I am getting "Connection refused" errors now.  I think someone changed
something server side.  I'll find out what is going on.

**Comment by bogdanni** [comment]
This is a GSFC server issue, closing.
