### ISSUE TITLE
Twice the same layer 

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/JHelioviewer-SWHV#69]
Hello, 

Starting JHelioviewer with the command line I have got twice the same layer 

<pre>
java -jar JHelioviewer.jar -request ./request.json 
</pre>

request.json containing : 
<pre>
 {
        "observatory": "SDO",
        "startTime": "2012-03-06 12:00:00",
        "endTime": "2012-03-06 20:00:00",
        "cadence": 3600,
        "dataset": "AIA 304"
}
</pre>

test done with last version available  jhv-2.13.1.8623

P. 
IAS

**Comment by bogdanni** [comment]
Confirmed.

**Comment by bogdanni** [comment]
The format was changed to:
```json
{
    "org.helioviewer.jhv.request.image": [
        {
            "startTime": "2012-03-06T12:00:00",
            "endTime": "2012-03-06T20:00:00",
            "dataset": "AIA 304"
        },
        {
            "startTime": "2012-03-06T12:00:00",
            "endTime": "2012-03-06T20:00:00",
            "dataset": "AIA 171"
        }
    ]
}
```
i.e., give the possibility to load an array of requests.

Time can be specified in natural language (English), e.g, `"startTime": "two days ago", "endTime": "now"`.
