### ISSUE TITLE
JHelioviewer 2.10: missing feature for image scroll bar

### ISSUE THREAD

**Issue by pryoung** [Helioviewer-Project/JHelioviewer-SWHV#7]
With the previous version of JHelioviewer you could click on the image slider bar and then use the keyboard cursor keys to slowly cycle through images. This was very useful if you were carefully studying some dynamic event and wanted to check how it is changing on a frame-by-frame basis. Using the mouse to do this is not very accurate.

This is the sort of missing feature that would drive me to go back to the previous version of JHelioviewer so I hope you can fix it.

Thanks, Peter.

**Comment by mablesly** [comment]
Dear Peter, 

A keyboard shortcut (for mac alt+n and alt+b are assigned to go to the previous and next frame. 

I hope this is sufficient for your purpose. In case it is not, we can consider optimisations. 

Best regards, 

Bram

**Comment by pryoung** [comment]
OK, that works. I guess I prefer the left-right arrow keys simply because I only need to use one hand (plus it used to work on the previous version).

Thanks, Peter.
