### ISSUE TITLE
Doc : How to use JHelioviewer in command line 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/JHelioviewer-SWHV#73]
Hello, 

Can we have a documentation about the use of JHelioviewer in command line with all the options available, some examples ...

Using http://swhv.oma.be/user_manual/ I don't find the info 

Best regards, 
P.
IAS

**Comment by bogdanni** [comment]
The documentation is not public yet.

**Comment by bogdanni** [comment]
Please give me a week.

**Comment by bogdanni** [comment]
Still didn't have time to document this.

Examples at http://swhv.oma.be/test/samp/ (can be loaded directly in JHV if running).
A bit more in https://github.com/Helioviewer-Project/JHelioviewer-SWHV/blob/master/docs/ddf.md in section "File Formats" (preliminary document, GitHub rendering may garble parts of it).

**Comment by bogdanni** [comment]
The user manual will be updated.
