### ISSUE TITLE
GONG data no longer available?

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer-SWHV#74]
I remember that, e.g., Halpha from GONG was available some days ago,
but there is no entry for this within Version 2.13.1.8623.
OS: FEDORA 28 X64
JAVA: java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc28.x86_64/jre/bin/java)

BTW, there is an error when selecting to connect NSFC datasets servers
![screenshot from 2018-05-25](https://user-images.githubusercontent.com/8266771/40525484-d9d9ae0a-6012-11e8-93e6-698e7a6b01f2.png)

and ROB server is not available

![screenshot from 2018-05-25 12-01-02](https://user-images.githubusercontent.com/8266771/40525572-6b9a1140-6013-11e8-827a-1858a5f4fba4.png)

**Comment by bogdanni** [comment]
ROB server is down, will be restarted later today.
GSFC server has trouble sending image data to JHV.
