### ISSUE TITLE
Specifying time: why do we need to input seconds?

### ISSUE THREAD

**Issue by pryoung** [Helioviewer-Project/JHelioviewer-SWHV#8]
OK, this has irritated me for a long time...when I type in a time range why do I have to type "10:30:00" instead of "10:30"? If I do the latter then it gets rejected and the time is reset back to "00:00:00".  I can't imagine anybody ever needs to have times specified to second accuracy, so please fix this!!

Also, please allow it to accept, e.g., simply "9" for 09:00.

Anyways, thanks for making a great product.  Peter.

**Comment by bogdanni** [comment]
This will be available in a new release next week. Thank you for the feedback.
