### ISSUE TITLE
Use case for off-disk corona toggle

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/JHelioviewer-SWHV#9]
What is the purpose of this feature?

**Comment by bogdanni** [comment]
If nobody cares about it, this inherited feature will be removed in a release later this week.

**Comment by dmueller3000** [comment]
Hi Bogdan, 

I believe this functionality is still needed to display, e.g. a set EUV images projected onto the solar sphere without off-limb 'artefacts' (e.g. STEREO-A,B SECCHI + SDO) so would like to keep it for the time being.

Thanks!

Daniel

**Comment by dmueller3000** [comment]
Example

![screen shot 2016-04-11 at 16 16 10](https://cloud.githubusercontent.com/assets/9073862/14430139/b686d064-0000-11e6-8b45-64ae75fe9a95.png)

**Comment by bogdanni** [comment]
OK, thanks, understood. We keep it.
