### ISSUE TITLE
Ability to set layer time step is missing in latest jhv-2.15.2.9166

### ISSUE THREAD

**Issue by superkuh** [Helioviewer-Project/JHelioviewer-SWHV#98]
In older versions of JHelioviewer (ie, jhv-2.11.3.8731) the "+ New Layer" button opened a new window in which among the various date and data source selections opens there was a "Time Step" option which allowed changing from "sec,min,hours,days,get all". With it you could see the chromospheric fibril motion resolved in time at the 10s time step. As long as the request was under 3 hours this came in at just under the API item request limit.

But now in the most recent JHelioviewer, jhv-2.15.2.9166, the layer date and all that have been integrated into the left toolbar. But the time step option is not there.

http://superkuh.com/jhelio_timestep.png

**Comment by bogdanni** [comment]
You can still get the full options window via File->New Image Layer or Ctrl-N.
