### ISSUE TITLE
Customise longitudinal projection grid

### ISSUE THREAD

**Issue by gpelouze** [Helioviewer-Project/JHelioviewer-SWHV#99]
Currently, the default grid that is displayed on top of the longitudinal projection seems to be the heliographic latitude for the y-axis, and the Carrington longitude +180° for the x-axis. 

When trying to change grid type (in the image layer panel), the longitudinal projection grid is not affected, which is a bit confusing. (I actually scratched my head for some time trying to figure out what was going on with the AIA data and the coordinates of an event I had computed.)

I have two suggestions to improve this behaviour: 

- Disable the grid layer configuration when using another projection than orthographic (or if this is not possible explicitly display what the axes are used in the longitudinal projection).
- Allow the grid to be customised (eg. choose between Carrington and Stonyhurst) for the longitudinal projection. I guess it would require more work, but it would also be really useful to users working with this projection.

Many thanks!

**Comment by bogdanni** [comment]
Agreed, the second bullet point is already on the to-do list!
Sorry for the current confusing behavior in the meanwhile...

**Comment by ArcturusB** [comment]
Awesome, thanks a lot for the quick reply!

**Comment by d-lamb** [comment]
> and the Carrington longitude +180° for the x-axis

Gabriel, thanks for pointing this out!
It was making me crazy when all of the Carrington longitudes I was computing and comparing with JHelioviewer were off by 180˚!

**Comment by bogdanni** [comment]
You can check with prerelease-2.16.0 from http://swhv.oma.be/download_test/ (macOS and Windows only for now) if the grid now correctly respects the settings.

**Comment by bogdanni** [comment]
It turned up harder than thought as it essentially becomes a drawing mode for the latitudinal projection. As a bonus, in grid type mode "Viewpoint", now it actually obeys the viewpoint setting, like it can be seen in the movie at http://swhv.oma.be/test/JHV_2020-01-30_15.56.45.mp4 .

**Comment by d-lamb** [comment]
When viewing data in the Orthographic projection, the grid obeys the settings for the desired Grid spacing in latitude and longitude.  But when switching the projection to Latitudinal, the grid spacing is 15˚ in longitude, 18˚ in latitude, regardless of the setting in the Grid panel.  Is that expected behavior, or a bug?  Now that I've installed Version 2.16.0.9870 I can't remember what the old behavior was.

**Comment by bogdanni** [comment]
That's expected as grid spacing customization was never implemented for non-orthographic projections ;)
